const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const stages=['立项','趋势验证','Demo MVP','小流量测试','规模转化'];
const stageColors=['#f0bd4d','#ff8b70','#4cc9c1','#5a9fdb','#786ae5'];
const storageKey='company-project-board-v1';
let selectedStage='all',selectedTrend='',searchTerm='',pendingProject='',pendingStage=null,toastTimer;
const seed={projects:[
 {id:'sleep',name:'轻量疗愈：睡前情绪陪伴',stage:2,trend:'反内耗生活',owner:'林阳（市场）',members:'陈语（产品）、夏青（运营）',intro:'为晚间高活跃的独居用户提供低门槛的情绪清空体验，验证连续使用与留存。',next:'完成 120 人封闭体验，验证连续 3 日留存。',progress:78,metrics:[{name:'Demo 完成度',value:'78%',source:'产品 Demo 检查表',note:'已完成核心引导和反馈闭环'},{name:'招募用户',value:'86 / 120',source:'用户招募名单',note:'封闭体验招募进度'},{name:'意向转化',value:'6.7%',source:'7/15 体验后问卷',note:'完成体验后选择继续使用的占比'}],tasks:[{id:'t1',title:'完成封闭体验招募',owner:'林阳（市场）',due:'2026-07-20',done:false,criteria:'招募满 120 名目标用户'}]},
 {id:'food',name:'AI 食谱：一周健康复刻',stage:2,trend:'一人食高级感',owner:'景珂（产品）',members:'心怡（增长）、徐安（算法）',intro:'把高收藏一人食内容变成可执行的个性化饮食计划，降低用户的选择成本。',next:'完成首批访谈，确定食谱生成的关键输入。',progress:54,metrics:[{name:'Demo 完成度',value:'54%',source:'产品需求清单',note:'食谱生成和收藏承接待完成'},{name:'招募用户',value:'42 / 100',source:'内测报名表',note:'待完成首批用户招募'},{name:'意向转化',value:'4.2%',source:'内测问卷',note:'持续观察中'}],tasks:[{id:'t2',title:'完成首批用户访谈',owner:'景珂（产品）',due:'2026-07-24',done:false,criteria:'完成 8 位目标用户深访'}]},
 {id:'city',name:'城市周末：兴趣活动匹配',stage:1,trend:'周末城市逃离',owner:'乔文（市场）',members:'唐可（产品）、宋越（运营）',intro:'让初到城市的新人更快发现同好活动，验证本地生活流量到活动报名的转化。',next:'等待确认 2 周测试预算与 3 城首批活动供给。',progress:31,metrics:[{name:'项目推进',value:'31%',source:'项目计划表',note:'等待资源确认后进入小流量测试'},{name:'测试城市',value:'0 / 3',source:'城市供给清单',note:'待确定首批测试城市'},{name:'预估转化',value:'5.1%',source:'历史活动报名数据',note:'仅为验证前预测'}],tasks:[{id:'t3',title:'确认三城测试预算',owner:'乔文（市场）',due:'2026-07-18',done:false,criteria:'获得总经办批准与预算编号'}]},
 {id:'work',name:'职场能量补给',stage:0,trend:'效率工具',owner:'徐安（产品）',members:'林阳（市场）、顾言（设计）',intro:'将碎片化的效率技巧转化为可持续执行的每日能量计划。',next:'补齐目标人群、核心假设与首轮验证指标。',progress:12,metrics:[{name:'立项完整度',value:'12%',source:'立项模板',note:'基础信息已录入'},{name:'趋势样本',value:'8 / 30',source:'内容采样表',note:'待补齐样本'},{name:'预估转化',value:'待测',source:'尚未形成数据',note:'完成趋势验证后录入'}],tasks:[]},
 {id:'pet',name:'城市养宠：新手陪伴',stage:3,trend:'新手养宠',owner:'夏青（运营）',members:'陈语（产品）、景珂（增长）',intro:'让新手养宠用户在关键节点获得正确且及时的行动建议。',next:'复盘首轮投放人群，优化从内容到工具的承接页。',progress:66,metrics:[{name:'测试预算',value:'68%',source:'投放台账',note:'首轮投放已消耗预算占比'},{name:'首批用户',value:'213',source:'落地页报名数据',note:'已完成报名的去重用户'},{name:'报名转化',value:'5.8%',source:'投放后台',note:'点击到报名的转化率'}],tasks:[{id:'t4',title:'复盘首轮投放人群',owner:'夏青（运营）',due:'2026-07-22',done:false,criteria:'输出人群复盘与下一轮投放建议'}]}
],trends:[
 {id:'anti',name:'反内耗生活',growth:'+126%',volume:'2.4M 播放',url:'https://example.com/trend/anti',project:'sleep',hypothesis:'用户是否愿意从情绪内容进入 5 分钟的引导式体验？',status:'已进入 Demo 验证'},
 {id:'food',name:'一人食高级感',growth:'+89%',volume:'1.8M 播放',url:'https://example.com/trend/food',project:'food',hypothesis:'个性化食谱是否能将收藏行为转化为一周计划？',status:'已进入 Demo 验证'},
 {id:'city',name:'周末城市逃离',growth:'+62%',volume:'956K 播放',url:'https://example.com/trend/city',project:'city',hypothesis:'用户是否愿意依据兴趣直接报名本地活动？',status:'等待资源确认'}
],activity:[{id:'a1',at:'2026-07-15',type:'初始化',text:'已载入演示项目、趋势与验证指标'}]};
let state=load();
function load(){try{const saved=localStorage.getItem(storageKey);return saved?JSON.parse(saved):structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(storageKey,JSON.stringify(state))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function uid(prefix){return `${prefix}-${Date.now().toString(36)}`}
function today(){return new Date().toISOString().slice(0,10)}
function log(text,type='更新'){state.activity.unshift({id:uid('a'),at:today(),type,text});state.activity=state.activity.slice(0,30);save()}
function notice(text){const node=$('.toast');node.textContent=text;node.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('show'),2800)}
function project(id){return state.projects.find(x=>x.id===id)}
function trendFor(projectId){return state.trends.find(x=>x.project===projectId)}
function renderCounts(){const counts=stages.map((_,i)=>state.projects.filter(p=>p.stage===i).length);$('#activeProjects').textContent=String(state.projects.length).padStart(2,'0');$('#activeTrends').textContent=String(state.trends.length).padStart(2,'0');$('#attentionCount').textContent=String(state.trends.filter(t=>t.status.includes('等待')).length+state.projects.filter(p=>p.tasks.some(t=>!t.done&&t.due<today())).length).padStart(2,'0');$('#allCount').textContent=String(state.projects.length).padStart(2,'0');counts.forEach((n,i)=>{$(`#stage${i}Count`).textContent=String(n).padStart(2,'0')})}
function filtered(){return state.projects.filter(p=>{const text=`${p.name} ${p.trend} ${p.owner}`.toLowerCase();return (selectedStage==='all'||p.stage===Number(selectedStage))&&(!selectedTrend||p.trend===selectedTrend)&&text.includes(searchTerm.toLowerCase())})}
function renderProjects(){const items=filtered();$('#projectRows').innerHTML=items.map(p=>`<article class="project-row" tabindex="0" data-project="${p.id}" role="row"><div class="project-name"><span class="project-dot" style="background:${stageColors[p.stage]}"></span><div><b>${esc(p.name)}</b><small>${esc(p.intro)}</small></div></div><div><span class="trend-chip"># ${esc(p.trend)}</span></div><div class="owner-cell">${esc(p.owner)}</div><div><span class="stage-pill" style="--stage:${stageColors[p.stage]}">${stages[p.stage]}</span><small class="cell-muted">${p.progress}% 已完成</small></div><div class="next-cell">${esc(p.next)}</div></article>`).join('');$('#emptyState').hidden=Boolean(items.length);const clues=[];if(selectedStage!=='all')clues.push(`「${stages[selectedStage]}」阶段`);if(selectedTrend)clues.push(`趋势「${selectedTrend}」`);if(searchTerm)clues.push(`搜索「${searchTerm}」`);$('#filterNote').textContent=clues.length?`当前显示 ${clues.join(' · ')}的 ${items.length} 个项目`:`当前显示全部 ${items.length} 个开发项目`}
function renderTrends(){$('#trendList').innerHTML=state.trends.map(t=>{const p=project(t.project);return `<button class="trend-card ${selectedTrend===t.name?'selected':''}" data-trend="${t.id}"><div class="trend-card-top"><b># ${esc(t.name)}</b><span class="trend-score">${esc(t.growth)}</span></div><p>${esc(t.volume)} · 关联「${esc(p?.name||'待关联')}」</p><small>${esc(t.status)}</small></button>`}).join('')}
function renderAll(){renderCounts();renderProjects();renderTrends();$('#trendProject').innerHTML=`<option value="">选择关联项目</option>${state.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}`}
function metricCard(m,index,p){return `<div class="metric-data"><div><span>${esc(m.name)}</span><b>${esc(m.value)}</b><small>来源：${esc(m.source)}</small></div><button data-edit-metric="${index}" data-project="${p.id}">维护</button></div>`}
function taskRow(t,p){return `<label class="task-row"><input type="checkbox" data-task="${t.id}" data-project="${p.id}" ${t.done?'checked':''}><span><b>${esc(t.title)}</b><small>${esc(t.owner)} · 截止 ${esc(t.due)} · ${esc(t.criteria)}</small></span></label>`}
function openDrawer(p){const t=trendFor(p.id);const stageButtons=stages.map((name,i)=>`<button class="${i===p.stage?'active':''}" data-stage-select="${i}" data-project="${p.id}">${i+1}. ${name}</button>`).join('');$('#drawerEyebrow').textContent=`项目详情 · ${stages[p.stage]}`;$('#drawerTitle').textContent=p.name;$('#drawerContent').innerHTML=`<section class="drawer-block"><h3>项目介绍</h3><p>${esc(p.intro)}</p></section><section class="drawer-block"><h3>趋势来源与假设</h3><p class="team-line"><b>验证趋势</b># ${esc(p.trend)}</p>${t?`<p class="data-source">来源：<a href="${esc(t.url)}" target="_blank" rel="noreferrer">${esc(t.volume)}，${esc(t.growth)} ↗</a></p><p class="data-hypothesis">验证假设：${esc(t.hypothesis)}</p>`:'<p class="data-hypothesis">尚未建立趋势映射</p>'}<p class="team-line"><b>负责人</b>${esc(p.owner)}</p><p class="team-line"><b>参与人员</b>${esc(p.members)}</p></section><section class="drawer-block"><div class="drawer-section-head"><h3>验证指标</h3><button data-add-metric="${p.id}">＋ 添加</button></div><div class="metric-data-list">${p.metrics.map((m,i)=>metricCard(m,i,p)).join('')}</div></section><section class="drawer-block"><h3>项目流转</h3><div class="stage-controls">${stageButtons}</div><button class="primary-btn advance-btn" data-advance="${p.id}" ${p.stage===4?'disabled':''}>${p.stage===4?'已进入规模转化':'申请推进至下一阶段 →'}</button></section><section class="drawer-block"><div class="drawer-section-head"><h3>下一步任务</h3><button data-add-task="${p.id}">＋ 添加</button></div><p class="next-summary">${esc(p.next)}</p><div class="task-list">${p.tasks.length?p.tasks.map(t=>taskRow(t,p)).join(''):'<p class="empty-inline">尚未添加任务，请明确下一步责任与完成标准。</p>'}</div></section><section class="drawer-block"><h3>最近记录</h3><div class="activity-list">${state.activity.filter(a=>a.text.includes(p.name)).slice(0,4).map(a=>`<p>${esc(a.at)} · ${esc(a.text)}</p>`).join('')||'<p>项目后续操作会记录在这里。</p>'}</div></section>`;$('#detailDrawer').classList.add('open');$('#drawerOverlay').classList.add('open');$('#detailDrawer').setAttribute('aria-hidden','false')}
function closeDrawer(){$('#detailDrawer').classList.remove('open');$('#drawerOverlay').classList.remove('open');$('#detailDrawer').setAttribute('aria-hidden','true')}
function setStage(stage){selectedStage=stage;$$('.stage-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.stage===String(stage)));renderProjects()}
function requestStage(projectId,target){const p=project(projectId);if(target===p.stage)return;pendingProject=projectId;pendingStage=target;$('#advanceTitle').textContent=`确认调整至「${stages[target]}」？`;$('#advanceCopy').textContent=`「${p.name}」将从「${stages[p.stage]}」调整为「${stages[target]}」。系统会保留本次变更记录。`;$('#advanceCheck').checked=false;$('#advanceDialog').showModal()}
function openMetric(projectId,index=null){const p=project(projectId),m=index===null?{name:'',value:'',source:'',note:''}:p.metrics[Number(index)];$('#metricDialogTitle').textContent=index===null?'添加验证指标':'维护验证指标';$('#metricProjectId').value=projectId;$('#metricIndex').value=index===null?'':index;$('#metricName').value=m.name;$('#metricValue').value=m.value;$('#metricSource').value=m.source;$('#metricNote').value=m.note||'';$('#metricDialog').showModal()}
function openTask(projectId){$('#taskProjectId').value=projectId;$('#taskDue').value=today();$('#taskForm').reset();$('#taskProjectId').value=projectId;$('#taskDue').value=today();$('#taskDialog').showModal()}
function showDataGuide(){const list=state.activity.slice(0,8).map(a=>`<p><b>${esc(a.at)}</b><span>${esc(a.type)} · ${esc(a.text)}</span></p>`).join('');$('#dataLog').innerHTML=`<h3>最近数据记录</h3>${list||'<p>暂无记录</p>'}`;$('#dataDialog').showModal()}

$('#addProject').addEventListener('click',()=>$('#projectDialog').showModal());$('#dataGuide').addEventListener('click',showDataGuide);$('#modelExplain').addEventListener('click',()=>$('#modelDialog').showModal());$('#modelExplainSecondary').addEventListener('click',()=>$('#modelDialog').showModal());
$('#newProjectSignal').addEventListener('change',e=>{const show=Boolean(e.target.value);$('#trendLinkField').classList.toggle('visible',show);$('#trendLink').required=show});$$('.dialog-close,.cancel-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
$('#projectForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#newProjectName').value.trim(),intro=$('#newProjectIntro').value.trim(),trend=$('#newProjectSignal').value,link=$('#trendLink').value.trim(),owner=$('#projectOwner').value.trim(),members=$('#projectMembers').value.trim();if(!name||!intro||!trend||!link||!owner||!members)return;const id=uid('p');state.projects.unshift({id,name,intro,trend,link,owner,members,stage:0,next:'请添加第一个可验证任务。',progress:0,metrics:[],tasks:[]});state.trends.unshift({id:uid('trend'),name, url:link,growth:'待录入',volume:'待录入',project:id,hypothesis:'待补充验证假设',status:'等待趋势确认'});log(`创建项目「${name}」并建立趋势来源`,'新增');save();$('#projectDialog').close();e.target.reset();$('#trendLinkField').classList.remove('visible');renderAll();setStage('0');notice(`「${name}」已立项，请继续添加指标和任务。`);openDrawer(project(id))});
$('#openTrendMap').addEventListener('click',()=>$('#trendDialog').showModal());$('#trendForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#trendName').value.trim(),url=$('#trendUrl').value.trim(),projectId=$('#trendProject').value,hypothesis=$('#trendHypothesis').value.trim();if(!name||!url||!projectId||!hypothesis)return;const p=project(projectId);p.trend=name;state.trends.unshift({id:uid('trend'),name,url,growth:'待录入',volume:'待录入',project:projectId,hypothesis,status:'等待趋势确认'});log(`将趋势「${name}」关联到项目「${p.name}」`,'趋势映射');save();$('#trendDialog').close();e.target.reset();selectedTrend=name;renderAll();notice(`趋势已关联到「${p.name}」。`)});
$('#stageTabs').addEventListener('click',e=>{const tab=e.target.closest('.stage-tab');if(tab)setStage(tab.dataset.stage)});$('#projectSearch').addEventListener('input',e=>{searchTerm=e.target.value.trim();renderProjects()});$('#clearFilter').addEventListener('click',()=>{selectedTrend='';searchTerm='';$('#projectSearch').value='';setStage('all');renderTrends()});$('#projectRows').addEventListener('click',e=>{const row=e.target.closest('.project-row');if(row)openDrawer(project(row.dataset.project))});$('#projectRows').addEventListener('keydown',e=>{if(e.key==='Enter'){const row=e.target.closest('.project-row');if(row)openDrawer(project(row.dataset.project))}});
$('#trendList').addEventListener('click',e=>{const card=e.target.closest('.trend-card');if(!card)return;const t=state.trends.find(x=>x.id===card.dataset.trend);selectedTrend=selectedTrend===t.name?'':t.name;setStage('all');renderTrends();notice(selectedTrend?`已筛选关联「${t.name}」的项目。`:'已显示全部项目。')});$('#resetTrend').addEventListener('click',()=>{selectedTrend='';renderProjects();renderTrends()});$('#drawerClose').addEventListener('click',closeDrawer);$('#drawerOverlay').addEventListener('click',closeDrawer);
$('#drawerContent').addEventListener('click',e=>{const stage=e.target.dataset.stageSelect,projectId=e.target.dataset.project;if(stage!==undefined)requestStage(projectId,Number(stage));if(e.target.dataset.advance){const p=project(e.target.dataset.advance);requestStage(p.id,Math.min(p.stage+1,4))}if(e.target.dataset.addMetric)openMetric(e.target.dataset.addMetric);if(e.target.dataset.editMetric!==undefined)openMetric(e.target.dataset.project,e.target.dataset.editMetric);if(e.target.dataset.addTask)openTask(e.target.dataset.addTask)});$('#drawerContent').addEventListener('change',e=>{if(!e.target.dataset.task)return;const p=project(e.target.dataset.project),task=p.tasks.find(t=>t.id===e.target.dataset.task);task.done=e.target.checked;log(`${task.done?'完成':'重新打开'}任务「${task.title}」`, '任务');save();openDrawer(p);renderAll()});
$('#advanceForm').addEventListener('submit',e=>{e.preventDefault();if(!pendingProject||pendingStage===null||!$('#advanceCheck').checked)return;const p=project(pendingProject),from=stages[p.stage];p.stage=pendingStage;p.progress=Math.min(100,p.progress+14);log(`项目「${p.name}」从「${from}」调整至「${stages[p.stage]}」`,'阶段流转');save();$('#advanceDialog').close();renderAll();openDrawer(p);notice(`已更新为「${stages[p.stage]}」。`);pendingProject='';pendingStage=null});
$('#metricForm').addEventListener('submit',e=>{e.preventDefault();const p=project($('#metricProjectId').value),index=$('#metricIndex').value,m={name:$('#metricName').value.trim(),value:$('#metricValue').value.trim(),source:$('#metricSource').value.trim(),note:$('#metricNote').value.trim()};if(!m.name||!m.value||!m.source)return;if(index==='')p.metrics.push(m);else p.metrics[Number(index)]=m;log(`${index===''?'添加':'更新'}项目「${p.name}」的指标「${m.name}」`, '指标');save();$('#metricDialog').close();renderAll();openDrawer(p);notice('指标与数据来源已保存。')});
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const p=project($('#taskProjectId').value),task={id:uid('task'),title:$('#taskTitle').value.trim(),owner:$('#taskOwner').value.trim(),due:$('#taskDue').value,criteria:$('#taskDone').value.trim(),done:false};if(!task.title||!task.owner||!task.due||!task.criteria)return;p.tasks.push(task);p.next=task.title;log(`为项目「${p.name}」添加任务「${task.title}」`, '任务');save();$('#taskDialog').close();renderAll();openDrawer(p);notice('任务已添加，并成为当前下一步。')});
$('#resetData').addEventListener('click',()=>{if(!confirm('将清除本地录入数据并恢复演示内容，是否继续？'))return;state=structuredClone(seed);save();$('#dataDialog').close();renderAll();closeDrawer();notice('已恢复演示数据。')});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});renderAll();
