const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const stages=['立项','趋势验证','Demo MVP','小流量测试','规模转化'];
const stageColors=['#f0bd4d','#ff8b70','#4cc9c1','#5a9fdb','#786ae5'];
const experimentMethods=['内容测试','用户访谈 / 问卷','可用性测试','Demo 测试','小流量投放','A/B 测试','数据分析','其他'];
const experimentDecisions=['继续验证','进入下一阶段','调整方向','暂停','终止','规模化'];
const appCategories={
  '工具与效率':['待办与日历','笔记与文档','AI 助手','扫描与识别','文件管理','浏览器与搜索','翻译工具','计算与换算','设备工具','开发者工具'],
  '社交与社区':['即时通讯','兴趣社区','熟人社交','陌生人社交','婚恋交友','职场人脉','语音社交','视频社交','家庭社交','本地社交'],
  '健康与身心':['运动健身','饮食营养','睡眠管理','冥想减压','心理健康','女性健康','慢病管理','医疗问诊','用药管理','健康数据'],
  '生活方式':['星座与玄学','美妆与穿搭','家居与家装','母婴与育儿','宠物服务','情感关系','兴趣爱好','习惯养成','本地生活','天气服务'],
  '内容与娱乐':['短视频','长视频与流媒体','音乐与音频','直播','阅读与小说','漫画','新闻资讯','图片与视频创作','票务与演出','游戏与互动娱乐'],
  '教育与成长':['语言学习','K12 教育','高等教育','职业技能','考试与认证','知识付费','儿童启蒙','阅读学习','编程教育','AI 学习'],
  '商业与金融':['移动支付','银行服务','投资理财','保险服务','记账与预算','电商购物','二手交易','企业协作','CRM 与营销','求职与招聘'],
  '出行与本地服务':['地图与导航','打车与租车','公共交通','旅行预订','攻略与导览','酒店与民宿','航班与铁路','汽车服务','餐饮与外卖','到店服务']
};
const ADMIN_EMAIL='luzw6688@gmail.com';
const config=window.APP_CONFIG||{};
const BUSINESS_TIME_ZONE=config.businessTimeZone||'Asia/Shanghai';
const db=window.supabase?.createClient(config.supabaseUrl,config.supabasePublishableKey);
let state={projects:[],trends:[],relations:[],activity:[],gateDefinitions:[],templates:[]},deletedProjects=[],currentUser=null,isAdmin=false;
let selectedStage='all',selectedTrend='',selectedCommandFilter='',searchTerm='',pendingProject='',pendingStage=null,pendingStageMode='advance',selectedTemplate='',activeDrawerTab=localStorage.getItem('projectDrawerTab')||'overview',drawerReturnFocus=null,lastDataUpdatedAt=null,toastTimer,realtimeChannel,reloadTimer;
const projectFilters={category:'',stage:'',owner:'',health:'',flag:'',sort:'updated'};
const stageDwellLimits=[14,14,21,14,30],priorityRank={高:3,中:2,低:1};

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function businessParts(date=new Date()){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:BUSINESS_TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]))}
function businessDayKey(date=new Date()){const p=businessParts(date);return `${p.year}-${p.month}-${p.day}`}
function shiftDayKey(key,days){const d=new Date(`${key}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function businessBoundary(key){const [year,month,day]=key.split('-').map(Number),guess=Date.UTC(year,month-1,day);const parts=new Intl.DateTimeFormat('en-US',{timeZone:BUSINESS_TIME_ZONE,year:'numeric',month:'numeric',day:'numeric',hour:'numeric',minute:'numeric',second:'numeric',hourCycle:'h23'}).formatToParts(new Date(guess)),values=Object.fromEntries(parts.filter(p=>p.type!=='literal').map(p=>[p.type,Number(p.value)])),asUtc=Date.UTC(values.year,values.month-1,values.day,values.hour,values.minute,values.second);return new Date(guess-(asUtc-guess))}
function today(){return businessDayKey()}
function project(id){return state.projects.find(x=>x.id===id)}
function trendsFor(projectId){return state.trends.filter(t=>t.projectIds.includes(projectId))}
function setSync(text,mode=''){$('#syncState').textContent=text;$('#syncState').className=`sync-state ${mode}`.trim()}
function notice(text){const node=$('.toast');node.textContent=text;node.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('show'),3000)}
function authMessage(text,type=''){$('#authMessage').textContent=text;$('#authMessage').className=`auth-message ${type}`.trim()}
function setBusy(form,busy){form.classList.toggle('saving-control',busy);$$('button,input,textarea,select',form).forEach(el=>el.disabled=busy)}
function requireAdmin(){if(isAdmin)return true;$('#authDialog').showModal();authMessage('请先使用管理员账号登录。');return false}

async function loadData({quiet=false}={}){
  if(!db){setSync('线上配置缺失','error');return}
  if(!quiet)setSync('正在同步…','saving');
  const [projectsRes,trendsRes,relationsRes,metricsRes,observationsRes,tasksRes,activityRes,gateDefinitionsRes,gatesRes,templateGatesRes,historyRes,experimentsRes,templatesRes,templateStatsRes]=await Promise.all([
    db.from('projects').select('*').order('created_at',{ascending:false}),
    db.from('trends').select('*').order('created_at',{ascending:false}),
    db.from('project_trends').select('*').order('created_at',{ascending:true}),
    db.from('metrics').select('*').order('position',{ascending:true}),
    db.from('metric_observations').select('*').order('measured_at',{ascending:false}).limit(2000),
    db.from('tasks').select('*').order('created_at',{ascending:true}),
    db.from('activity_logs').select('*').order('created_at',{ascending:false}).limit(1000),
    db.from('stage_gate_definitions').select('*').order('stage',{ascending:true}).order('position',{ascending:true}),
    db.from('project_stage_gates').select('*').order('created_at',{ascending:true}),
    db.from('project_template_gates').select('*').order('stage',{ascending:true}),
    db.from('stage_history').select('*').order('created_at',{ascending:false}).limit(1000),
    db.from('validation_experiments').select('*').order('created_at',{ascending:false}).limit(1000),
    db.from('validation_templates').select('*').order('updated_at',{ascending:false}),
    db.rpc('template_usage_stats')
  ]);
  const failure=[projectsRes,trendsRes,relationsRes,metricsRes,observationsRes,tasksRes,activityRes,gateDefinitionsRes,gatesRes,templateGatesRes,historyRes,experimentsRes,templatesRes,templateStatsRes].find(r=>r.error);
  if(failure){setSync('同步失败','error');notice(`线上数据读取失败：${failure.error.message}`);return}
  deletedProjects=projectsRes.data.filter(p=>p.deleted_at);
  const activeRows=projectsRes.data.filter(p=>!p.deleted_at);
  state.projects=activeRows.map(p=>({
    ...p,
    metrics:metricsRes.data.filter(m=>m.project_id===p.id).map(m=>({...m,observations:observationsRes.data.filter(o=>o.metric_id===m.id).sort((a,b)=>new Date(b.measured_at)-new Date(a.measured_at))})),
    tasks:tasksRes.data.filter(t=>t.project_id===p.id),
    gates:gatesRes.data.filter(g=>g.project_id===p.id),
    templateGates:templateGatesRes.data.filter(g=>g.project_id===p.id),
    history:historyRes.data.filter(h=>h.project_id===p.id),
    experiments:experimentsRes.data.filter(e=>e.project_id===p.id).sort((a,b)=>b.round_no-a.round_no)
  }));
  state.relations=relationsRes.data.filter(r=>activeRows.some(p=>p.id===r.project_id));
  state.trends=trendsRes.data.map(t=>{const mappings=state.relations.filter(r=>r.trend_id===t.id);return {...t,mappings,projectIds:mappings.map(r=>r.project_id)}}).filter(t=>t.projectIds.length||isAdmin);
  state.activity=activityRes.data.map(a=>({...a,at:businessDayKey(new Date(a.created_at))}));
  state.gateDefinitions=gateDefinitionsRes.data;
  state.templates=templatesRes.data.map(t=>({...t,...(templateStatsRes.data.find(s=>s.template_id===t.id)||{usage_count:0,success_count:0})}));
  lastDataUpdatedAt=new Date();
  renderAll();
  setSync(`已同步 · ${new Date().toLocaleTimeString('zh-CN',{timeZone:BUSINESS_TIME_ZONE,hour:'2-digit',minute:'2-digit'})}`,'online');
}

async function writeLog(projectId,text,type='更新'){
  const {error}=await db.from('activity_logs').insert({project_id:projectId||null,text,type,actor_email:currentUser?.email||ADMIN_EMAIL});
  if(error)throw error;
}

async function mutate(action,successText){
  if(!requireAdmin())return false;
  setSync('正在保存…','saving');
  try{await action();await loadData({quiet:true});if(successText)notice(successText);return true}
  catch(error){setSync('保存失败','error');notice(`保存失败：${error.message||error}`);return false}
}

function renderAuth(){
  isAdmin=currentUser?.email?.toLowerCase()===ADMIN_EMAIL;
  $$('.admin-only').forEach(node=>node.hidden=!isAdmin);
  $('#authButton').textContent=isAdmin?'退出管理员账号':'管理员登录';
  $('#topUserInitial').textContent=isAdmin?'ML':'访';$('#topUserName').textContent=isAdmin?'曼斯菲尔德':'公开访客';$('#topUserRole').textContent=isAdmin?'管理员 · 可编辑':'访客 · 只读查看';$('#topUserEmail').textContent=isAdmin?currentUser.email:'无需登录即可查看';
  document.body.classList.toggle('is-admin',isAdmin);
}

function renderCycle(){const p=businessParts(),year=Number(p.year),month=Number(p.month),quarter=Math.floor((month-1)/3)+1,quarterStartMonth=(quarter-1)*3+1,currentKey=`${p.year}-${p.month}-${p.day}`,startKey=`${year}-${String(quarterStartMonth).padStart(2,'0')}-01`,week=Math.floor((new Date(`${currentKey}T12:00:00Z`)-new Date(`${startKey}T12:00:00Z`))/604800000)+1,totalWeeks=Math.ceil((new Date(Date.UTC(year,quarter*3,1))-new Date(Date.UTC(year,quarterStartMonth-1,1)))/604800000);$('#currentQuarter').textContent=`${year} · Q${quarter}`;$('#currentQuarterWeek').textContent=`季度第 ${week} / ${totalWeeks} 周`;$('#businessTimezone').textContent=`业务时区 · ${BUSINESS_TIME_ZONE}`}

function renderCounts(){
  const stats=decisionStats();
  const values={activeProjects:stats.active.current,weeklyConclusions:stats.conclusions.current,pendingDecisions:stats.pending.current,riskProjects:stats.risk.current};
  Object.entries(values).forEach(([id,value])=>{$(`#${id}`).textContent=String(value).padStart(2,'0')});
  [['activeProjectsDelta',stats.active],['weeklyConclusionsDelta',stats.conclusions],['pendingDecisionsDelta',stats.pending],['riskProjectsDelta',stats.risk]].forEach(([id,data])=>renderDelta(id,data.current-data.previous));
  const updatedAt=(lastDataUpdatedAt||new Date()).toLocaleTimeString('zh-CN',{timeZone:BUSINESS_TIME_ZONE,hour:'2-digit',minute:'2-digit'});$('#decisionWeekRange').textContent=`本周 ${formatShortDate(stats.weekStart)} — ${formatShortDate(stats.weekEnd)} · ${BUSINESS_TIME_ZONE}`;$('#decisionUpdatedAt').textContent=`最近更新 ${updatedAt}`;renderCycle();
  $('#riskIssueCount').textContent=String(riskIssues().length);
  $$('[data-command-filter]').forEach(card=>{const active=selectedCommandFilter===card.dataset.commandFilter,alert=Number(card.querySelector('strong').textContent)>0;card.classList.toggle('active',active);card.classList.toggle('has-alert',alert);card.setAttribute('aria-pressed',String(active))});
  renderStageFunnel();
}

function stageEnteredAt(p){
  const history=p.history?.find(h=>h.to_stage===p.stage);
  if(history){const value=new Date(history.created_at);if(Number.isFinite(value.getTime()))return value}
  const marker=`调整至「${stages[p.stage]}」`;
  const entry=state.activity.find(a=>a.project_id===p.id&&a.type==='阶段流转'&&a.text.includes(marker));
  const value=new Date(entry?.created_at||p.created_at);
  return Number.isFinite(value.getTime())?value:new Date();
}
function gateDefinitions(stage){return state.gateDefinitions.filter(g=>g.stage===stage)}
function gateStatus(p,stage=p.stage){const definitions=gateDefinitions(stage),completed=new Set(p.gates.filter(g=>g.stage===stage&&g.completed).map(g=>g.gate_key)),missing=definitions.filter(g=>g.required&&!completed.has(g.gate_key));return {definitions,completed,missing,done:definitions.filter(g=>completed.has(g.gate_key)).length,total:definitions.length}}
function experimentComplete(e){return Boolean(e.completed_at&&e.conclusion?.trim()&&e.decision)}
function hasCompletedStageExperiment(p,stage=p.stage){return p.experiments.some(e=>e.stage===stage&&experimentComplete(e))}
function latestObservation(m){return m.observations?.[0]||null}
function metricStatus(m){const o=latestObservation(m);if(!o||!Number.isFinite(Number(o.value))||Number(o.sample_size)<=0)return '数据不足';const value=Number(o.value),target=Number(m.target_value),baseline=Number(m.baseline_value),passed=m.comparison_operator==='>'?value>target:m.comparison_operator==='>='?value>=target:m.comparison_operator==='<'?value<target:value<=target;if(passed)return '达标';const tolerance=Math.max(Math.abs(target-baseline)*.2,Math.abs(target)*.1,.0001),near=['>','>='].includes(m.comparison_operator)?value>=target-tolerance:value<=target+tolerance;return near?'接近目标':'未达标'}
function advanceRequirements(p){const missing=gateStatus(p).missing.map(g=>({type:'gate',label:g.label}));(p.templateGates||[]).filter(g=>g.stage===p.stage&&!g.completed).forEach(g=>missing.push({type:'gate',label:`模板门槛：${g.label}`}));if(p.stage<4&&!hasCompletedStageExperiment(p))missing.push({type:'experiment',label:`完成至少一轮「${stages[p.stage]}」验证实验，并填写结论与最终决策`});p.metrics.filter(m=>m.stage===p.stage&&m.is_key&&metricStatus(m)!=='达标').forEach(m=>missing.push({type:'metric',label:`关键指标「${m.name}」当前为“${metricStatus(m)}”，需达到目标后推进`}));return missing}
function stageFunnelStats(){
  const total=state.projects.length;
  return stages.map((_,stage)=>{const projects=state.projects.filter(p=>p.stage===stage),dwell=projects.map(projectDwell);return {count:projects.length,share:total?Math.round(projects.length/total*100):0,average:dwell.length?dwell.reduce((sum,n)=>sum+n,0)/dwell.length:0,overdue:projects.filter(p=>p.tasks.some(t=>!t.done&&t.due<today())).length}});
}
function renderStageFunnel(){
  const stats=stageFunnelStats();
  $('#allCount').textContent=String(state.projects.length).padStart(2,'0');
  stats.forEach((item,i)=>{$(`#stage${i}Count`).textContent=String(item.count).padStart(2,'0');$(`#stage${i}Share`).textContent=`${item.share}%`;$(`#stage${i}Dwell`).textContent=`${item.average.toFixed(1)} 天`;$(`#stage${i}Overdue`).textContent=String(item.overdue);$(`#stage${i}Bar`).style.width=`${item.share}%`;const tab=$(`.stage-tab[data-stage="${i}"]`);tab.classList.toggle('has-overdue',item.overdue>0)});
}

function startOfWeek(date=new Date()){const key=businessDayKey(date),calendar=new Date(`${key}T12:00:00Z`),offset=(calendar.getUTCDay()+6)%7;return businessBoundary(shiftDayKey(key,-offset))}
function endOfWeek(start){return businessBoundary(shiftDayKey(businessDayKey(start),7))}
function inRange(value,start,end){const time=new Date(value).getTime();return Number.isFinite(time)&&time>=start.getTime()&&time<end.getTime()}
function formatShortDate(date){return date.toLocaleDateString('zh-CN',{timeZone:BUSINESS_TIME_ZONE,month:'numeric',day:'numeric'})}
function formatBusinessDateTime(value,options={}){return new Date(value).toLocaleString('zh-CN',{timeZone:BUSINESS_TIME_ZONE,...options})}
function renderDelta(id,delta){const node=$(`#${id}`);node.textContent=delta===0?'与上周持平':`较上周 ${delta>0?'+':''}${delta}`;node.classList.toggle('is-up',delta>0);node.classList.toggle('is-down',delta<0)}
function conclusionLogs(start,end){return state.activity.filter(a=>['指标','阶段流转','趋势结论','阶段结论','验证结论'].includes(a.type)&&inRange(a.created_at,start,end))}
function isPendingConclusion(a){return ['指标','趋势结论','阶段结论'].includes(a.type)||(a.type==='验证结论'&&/(进入下一阶段|规模化)/.test(a.text))}
function pendingDecisionIds(end=new Date()){return new Set(state.projects.filter(p=>{const logs=state.activity.filter(a=>a.project_id===p.id&&new Date(a.created_at)<end);const conclusion=logs.find(isPendingConclusion);const decision=logs.find(a=>a.type==='阶段流转');return conclusion&&(!decision||new Date(conclusion.created_at)>new Date(decision.created_at))}).map(p=>p.id))}
function daysBetween(from,to=new Date()){const fromKey=/^\d{4}-\d{2}-\d{2}$/.test(String(from))?String(from):businessDayKey(new Date(from)),toKey=/^\d{4}-\d{2}-\d{2}$/.test(String(to))?String(to):businessDayKey(new Date(to));return Math.max(0,Math.floor((new Date(`${toKey}T12:00:00Z`)-new Date(`${fromKey}T12:00:00Z`))/86400000))}
function nextTask(p){return p.tasks.filter(t=>!t.done).sort((a,b)=>String(a.due).localeCompare(String(b.due))||(priorityRank[b.priority]||2)-(priorityRank[a.priority]||2))[0]||null}
function riskIssues(projects=state.projects,asOf=new Date()){
  const day=businessDayKey(asOf),soonDay=shiftDayKey(day,3),pending=pendingDecisionIds(new Date(asOf.getTime()+1));
  return projects.flatMap(p=>{const items=[],dwell=daysBetween(stageEnteredAt(p),asOf),add=(type,level,owner,since,action,ref='')=>items.push({id:`${p.id}:${type}:${ref}`,projectId:p.id,project:p.name,type,level,owner:owner||p.owner,duration:Math.max(0,daysBetween(since,asOf)),action});
    p.tasks.filter(t=>!t.done).forEach(t=>{if(t.due<day)add('逾期任务','高',t.owner,t.due,'立即确认阻塞原因并重排截止时间',t.id);else if(t.due<=soonDay)add('即将到期任务','中',t.owner,t.created_at,'确认交付物与按期完成把握',t.id);if(t.confirmation_status==='pending')add('等待负责人确认','中',t.owner,t.created_at,'负责人确认接单，或重新分配任务',t.id)});
    if(dwell>stageDwellLimits[p.stage])add('阶段停留超时',dwell>stageDwellLimits[p.stage]+7?'高':'中',p.owner,stageEnteredAt(p),'复盘阶段阻塞项并形成推进或终止决策');
    p.metrics.filter(m=>m.stage===p.stage&&m.is_key).forEach(m=>{const status=metricStatus(m),o=latestObservation(m);if(status!=='达标')add('指标未达标',status==='未达标'?'高':'中',p.owner,o?.measured_at||m.created_at,status==='数据不足'?`补充「${m.name}」的有效样本与本期数据`:`补充实验或调整方案，使「${m.name}」达到目标`,m.id)});p.metrics.filter(m=>m.stage===p.stage).forEach(m=>{const o=latestObservation(m);if(!o?.source_name||!o?.source_url)add('缺少数据来源','中',p.owner,o?.measured_at||m.created_at,`补齐「${m.name}」的数据来源名称与链接`,m.id)});
    if(pending.has(p.id))add('等待管理层决策','高',p.owner,state.activity.find(a=>a.project_id===p.id&&isPendingConclusion(a))?.created_at||p.updated_at,'管理层确认继续、调整、暂停或终止');
    return items});
}
function riskProjectIds(cutoff=today()){const date=new Date(businessBoundary(shiftDayKey(cutoff,1)).getTime()-1);return new Set(riskIssues(state.projects,date).map(i=>i.projectId))}
function projectHealth(p){const issues=riskIssues([p]);return issues.some(i=>i.level==='高')?'风险':issues.length?'关注':'健康'}
function healthClass(value){return value==='风险'?'risk':value==='关注'?'watch':'healthy'}
function decisionStats(){
  const weekStart=startOfWeek(),weekEnd=endOfWeek(weekStart),previousStart=businessBoundary(shiftDayKey(businessDayKey(weekStart),-7));
  const pendingNow=pendingDecisionIds(),pendingPrevious=pendingDecisionIds(weekStart),riskNow=riskProjectIds(),riskPrevious=riskProjectIds(businessDayKey(weekStart));
  const completedValidations=(start,end)=>state.projects.flatMap(p=>p.experiments||[]).filter(e=>e.completed_at&&inRange(e.completed_at,start,end)).length;
  return {weekStart,weekEnd:new Date(weekEnd.getTime()-1),pendingIds:pendingNow,riskIds:riskNow,
    active:{current:state.projects.length,previous:state.projects.filter(p=>new Date(p.created_at)<weekStart).length},
    conclusions:{current:completedValidations(weekStart,weekEnd),previous:completedValidations(previousStart,weekStart)},
    pending:{current:pendingNow.size,previous:pendingPrevious.size},
    risk:{current:riskNow.size,previous:riskPrevious.size}};
}

function projectDwell(p){return daysBetween(stageEnteredAt(p))}
function projectRiskRank(p){return ({风险:3,关注:2,健康:1})[projectHealth(p)]}
function filtered(){const stats=decisionStats(),commandIds=selectedCommandFilter==='risk'?stats.riskIds:stats.pendingIds;let items=state.projects.filter(p=>{const related=trendsFor(p.id),text=`${p.name} ${p.intro} ${p.category} ${p.subcategory} ${p.owner} ${related.map(t=>t.name).join(' ')}`.toLowerCase(),commandMatch=!selectedCommandFilter||commandIds.has(p.id),trendMatch=!selectedTrend||related.some(t=>t.id===selectedTrend),health=projectHealth(p),overdue=p.tasks.some(t=>!t.done&&t.due<today());return commandMatch&&(selectedStage==='all'||p.stage===Number(selectedStage))&&trendMatch&&text.includes(searchTerm.toLowerCase())&&(!projectFilters.category||p.category===projectFilters.category)&&(!projectFilters.stage||p.stage===Number(projectFilters.stage))&&(!projectFilters.owner||p.owner===projectFilters.owner)&&(!projectFilters.health||health===projectFilters.health)&&(!projectFilters.flag||(projectFilters.flag==='overdue'?overdue:stats.pendingIds.has(p.id)))});return items.sort((a,b)=>projectFilters.sort==='due'?String(nextTask(a)?.due||'9999').localeCompare(String(nextTask(b)?.due||'9999')):projectFilters.sort==='risk'?projectRiskRank(b)-projectRiskRank(a):projectFilters.sort==='dwell'?projectDwell(b)-projectDwell(a):new Date(b.updated_at)-new Date(a.updated_at))}

function renderProjects(){
  const items=filtered();
  $('#projectRows').innerHTML=items.map(p=>{const task=nextTask(p),health=projectHealth(p),metric=p.metrics.find(m=>m.stage===p.stage&&m.is_key),status=metric?metricStatus(metric):'数据不足',overdue=task&&task.due<today();return `<article class="project-row" tabindex="0" data-project="${p.id}" role="row"><div class="project-name"><span class="project-dot" style="background:${stageColors[p.stage]}"></span><div><b>${esc(p.name)}</b><small>${esc(p.intro)}</small><span class="mobile-taxonomy">${esc(p.category||'未分类')} · ${esc(p.subcategory||'待补充')}</span></div></div><div class="stage-cell"><span class="stage-pill" style="--stage:${stageColors[p.stage]}">${stages[p.stage]}</span><small class="cell-muted">停留 ${projectDwell(p)} 天 · ${p.progress}%</small></div><div><span class="health-pill ${healthClass(health)}">${health}</span><small class="cell-muted">${riskIssues([p]).length} 个问题</small></div><div class="core-metric-cell"><b>${esc(metric?.name||'尚未设关键指标')}</b><span class="metric-status ${metricStatusClass(status)}">${esc(status)}</span></div><div class="owner-cell">${esc(p.owner)}</div><div class="next-cell"><b>${esc(task?.title||'暂无未完成任务')}</b><small class="${overdue?'is-overdue':''}">${task?`${esc(task.priority||'中')}优先 · ${esc(task.due)}`:'请添加下一步任务'}</small></div></article>`}).join('');
  $('#emptyState').hidden=Boolean(items.length);
  const hasFilter=selectedStage!=='all'||selectedTrend||selectedCommandFilter||searchTerm||Object.values(projectFilters).some((v,i)=>i<5&&v);
  $('#emptyTitle').textContent=hasFilter?'未找到匹配的项目':'暂无进行中的项目';
  $('#emptyCopy').textContent=hasFilter?'尝试切换阶段，或清除当前筛选。':'管理员创建第一个项目后，所有访问者都能在这里看到最新进展。';
  const selectedTrendRecord=state.trends.find(t=>t.id===selectedTrend),clues=[];if(selectedCommandFilter)clues.push(selectedCommandFilter==='decision'?'「待决策项目」':'「风险项目」');if(selectedStage!=='all')clues.push(`「${stages[selectedStage]}」阶段`);if(selectedTrendRecord)clues.push(`趋势「${selectedTrendRecord.name}」`);if(searchTerm)clues.push(`搜索「${searchTerm}」`);
  $('#filterNote').textContent=clues.length?`当前显示 ${clues.join(' · ')}的 ${items.length} 个项目`:`当前显示 ${items.length} 个项目 · 筛选与排序会保留在网址中`;
}

function renderTrends(){
  const heading=$('#trends .panel-head h2');let count=$('.panel-count',heading.parentElement);if(!count){count=document.createElement('span');count.className='panel-count';heading.insertAdjacentElement('afterend',count)}count.textContent=`${state.trends.length} 条趋势`;
  $('#trendList').innerHTML=state.trends.length?state.trends.map(t=>{const names=t.projectIds.map(id=>project(id)?.name).filter(Boolean),summary=names.length<=2?names.join('、'):`${names.slice(0,2).join('、')} 等 ${names.length} 个项目`;return `<article class="trend-card-shell"><button class="trend-card ${selectedTrend===t.id?'selected':''}" data-trend="${t.id}" type="button"><div class="trend-card-top"><b># ${esc(t.name)}</b><span class="trend-score">${esc(t.growth)}</span></div><p>${esc(t.source_platform)} · ${esc(t.volume)} · 关联 ${esc(summary||'待关联')}</p><small>${esc(t.status)} · 可信度 ${esc(t.confidence)}</small></button>${isAdmin?`<button class="trend-edit" type="button" data-edit-trend="${t.id}">维护</button>`:''}</article>`}).join(''):'<p class="empty-inline">暂无趋势记录。管理员可以从第一个市场信号开始建立项目关系。</p>';
}

function renderFilterOptions(){
  const keep=(id,values,placeholder)=>{const node=$(`#${id}`),value=node.value;node.innerHTML=`<option value="">${placeholder}</option>${values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}`;node.value=value};
  keep('filterCategory',[...new Set(state.projects.map(p=>p.category).filter(Boolean))].sort(),'全部类别');
  keep('filterOwner',[...new Set(state.projects.map(p=>p.owner).filter(Boolean))].sort(),'全部负责人');
  const stageNode=$('#filterStage'),stageValue=stageNode.value;stageNode.innerHTML=`<option value="">全部阶段</option>${stages.map((v,i)=>`<option value="${i}">${v}</option>`).join('')}`;stageNode.value=stageValue;
}
function renderRiskCenter(){const all=riskIssues(),level=$('#riskLevelFilter').value,owner=$('#riskOwnerFilter').value,owners=[...new Set(all.map(i=>i.owner).filter(Boolean))].sort(),ownerNode=$('#riskOwnerFilter'),old=ownerNode.value;ownerNode.innerHTML=`<option value="">全部负责人</option>${owners.map(v=>`<option>${esc(v)}</option>`).join('')}`;ownerNode.value=old;const items=all.filter(i=>(!level||i.level===level)&&(!owner||i.owner===owner));$('#riskSummary').textContent=`${new Set(all.map(i=>i.projectId)).size} 个风险项目 · ${all.length} 个具体问题`;$('#riskList').innerHTML=items.length?items.map(i=>`<article class="risk-item level-${i.level}"><div class="risk-item-head"><span>${esc(i.type)}</span><em>${esc(i.level)}风险</em></div><button type="button" data-risk-project="${i.projectId}">${esc(i.project)} →</button><dl><div><dt>负责人</dt><dd>${esc(i.owner)}</dd></div><div><dt>持续时间</dt><dd>${i.duration} 天</dd></div></dl><p><b>建议动作</b>${esc(i.action)}</p></article>`).join(''):'<div class="risk-empty"><b>当前没有匹配的风险</b><span>问题解决后会自动从这里移除。</span></div>'}
function templateLines(value){return Array.isArray(value)?value.map(v=>typeof v==='string'?v:(v.title||v.name||JSON.stringify(v))).join('、'):'—'}
function renderTemplates(){const selectOptions=state.templates.map(t=>`<option value="${t.id}">${esc(t.name)} · v${t.version}</option>`).join('');$('#creationTemplate').innerHTML=`<option value="">请选择模板</option>${selectOptions}`;$('#templateList').innerHTML=state.templates.length?state.templates.map(t=>{const count=Number(t.usage_count||0),success=Number(t.success_count||0),rate=count?Math.round(success/count*100):0;return `<article class="template-card"><div class="template-card-head"><span>v${t.version} · ${esc(t.opportunity_type)}</span><b>${esc(t.name)}</b></div><p>${esc(t.target_audience)}</p><dl><div><dt>验证方式</dt><dd>${esc(templateLines(t.recommended_methods))}</dd></div><div><dt>预计周期</dt><dd>${esc(t.estimated_cycle)}</dd></div><div><dt>使用 / 成功率</dt><dd>${count} 次 · ${rate}%</dd></div></dl><div class="template-card-foot"><small>${esc(t.created_by)} · ${new Date(t.updated_at).toLocaleDateString('zh-CN',{timeZone:BUSINESS_TIME_ZONE})}</small><button type="button" data-use-template="${t.id}">从模板创建 →</button></div>${count?`<details><summary>参考历史项目</summary>${state.projects.filter(p=>p.template_id===t.id).map(p=>`<button type="button" data-template-project="${p.id}">${esc(p.name)} · ${stages[p.stage]}</button>`).join('')}</details>`:''}</article>`}).join(''):'<div class="template-empty"><b>暂无验证模板</b><span>规模转化阶段的项目可以一键提炼为团队模板。</span></div>'}

function renderTrash(){
  $('#trashList').innerHTML=deletedProjects.length?deletedProjects.map(p=>`<div class="trash-item"><div><b>${esc(p.name)}</b><small>删除于 ${new Date(p.deleted_at).toLocaleString('zh-CN',{timeZone:BUSINESS_TIME_ZONE})}</small></div><button type="button" data-restore-project="${p.id}">恢复项目</button></div>`).join(''):'<p class="empty-inline">暂无已删除项目。</p>';
}

function renderAll(){
  renderFilterOptions();renderCounts();renderProjects();renderTrends();renderTemplates();renderTrash();renderAuth();
  if($('#riskDrawer').classList.contains('open'))renderRiskCenter();
}

function metricOperatorLabel(value){return ({'>':'大于','>=':'大于等于','<':'小于','<=':'小于等于'})[value]||value}
function metricStatusClass(status){return ({'达标':'passed','接近目标':'near','未达标':'failed','数据不足':'insufficient'})[status]||'insufficient'}
function metricTrendSvg(m){const items=[...(m.observations||[])].reverse(),values=items.map(o=>Number(o.value)).filter(Number.isFinite);if(!values.length)return '<div class="metric-no-trend">暂无周期数据</div>';const min=Math.min(...values),max=Math.max(...values),range=max-min||1,points=values.map((value,i)=>`${values.length===1?70:4+i*132/(values.length-1)},${28-(value-min)/range*22}`).join(' '),latest=values.at(-1),previous=values.length>1?values.at(-2):null,change=previous===null?'首期数据':`较上期 ${latest-previous>=0?'+':''}${(latest-previous).toLocaleString('zh-CN')} ${m.unit}`;return `<div class="metric-trend"><svg viewBox="0 0 140 34" role="img" aria-label="${esc(m.name)} 共 ${values.length} 期变化趋势"><polyline points="${points}"></polyline>${points.split(' ').map(point=>{const [cx,cy]=point.split(',');return `<circle cx="${cx}" cy="${cy}" r="2.2"></circle>`}).join('')}</svg><span>${items.length} 期 · ${esc(change)}</span></div>`}
function metricCard(m,p){const latest=latestObservation(m),status=metricStatus(m),source=latest&&/^https?:\/\//i.test(latest.source_url)?`<a href="${esc(latest.source_url)}" target="_blank" rel="noreferrer">${esc(latest.source_name)} ↗</a>`:esc(latest?.source_name||'暂无来源'),history=(m.observations||[]).slice(0,3).map(o=>`<li><time>${esc(o.period_start)} — ${esc(o.period_end)}</time><b>${Number(o.value).toLocaleString('zh-CN')} ${esc(m.unit)}</b><span>n=${Number(o.sample_size||0).toLocaleString('zh-CN')}</span></li>`).join('');return `<article class="metric-card ${metricStatusClass(status)}"><div class="metric-card-head"><div><span>${esc(stages[m.stage])}${m.is_key?' · 关键指标':''}</span><h4>${esc(m.name)}</h4></div><em class="metric-status ${metricStatusClass(status)}">${esc(status)}</em></div><div class="metric-current"><strong>${latest?Number(latest.value).toLocaleString('zh-CN'):'—'} <small>${esc(m.unit)}</small></strong><span>目标 ${esc(metricOperatorLabel(m.comparison_operator))} ${Number(m.target_value).toLocaleString('zh-CN')} ${esc(m.unit)}</span></div><div class="metric-reference"><span>基准值 <b>${Number(m.baseline_value).toLocaleString('zh-CN')} ${esc(m.unit)}</b></span><span>样本量 <b>${latest?Number(latest.sample_size||0).toLocaleString('zh-CN'):'—'}</b></span></div>${metricTrendSvg(m)}<ul class="metric-history">${history||'<li>暂无周期数据</li>'}</ul><div class="metric-source"><span>来源：${source}</span><span>更新：${latest?formatBusinessDateTime(latest.measured_at):'—'}</span></div>${latest?.methodology?`<details><summary>查看口径说明</summary><p>${esc(latest.methodology)}</p></details>`:''}${isAdmin?`<div class="metric-actions"><button data-edit-metric="${m.id}" data-project="${p.id}">维护定义</button><button data-add-observation="${m.id}" data-project="${p.id}">＋ 新一期</button></div>`:''}</article>`}
function taskRow(t,p){return `<div class="task-row ${!t.done&&t.due<today()?'overdue':''}"><label><input type="checkbox" data-task="${t.id}" data-project="${p.id}" ${t.done?'checked':''} ${isAdmin?'':'disabled'}><span><b>${esc(t.title)}</b><small>${esc(t.priority||'中')}优先 · ${esc(t.owner)} · 截止 ${esc(t.due)}${t.confirmation_status==='pending'?' · 等待确认':''}</small><em>${esc(t.criteria)}</em></span></label>${isAdmin&&t.confirmation_status==='pending'&&!t.done?`<button type="button" data-confirm-task="${t.id}" data-project="${p.id}">确认接单</button>`:''}</div>`}
function thresholdLabel(e){return `${e.threshold_operator} ${Number(e.threshold_value).toLocaleString('zh-CN')} ${esc(e.threshold_unit)}`}
function sourceMarkup(value){const text=esc(value);return /^https?:\/\//i.test(value)?`<a href="${text}" target="_blank" rel="noreferrer">查看数据来源 ↗</a>`:text}
function experimentTimeline(p){return p.experiments.length?p.experiments.map(e=>{const complete=experimentComplete(e),result=e.threshold_met===true?'达标':e.threshold_met===false?'未达标':'待结果',tone=e.threshold_met===true?'passed':e.threshold_met===false?'failed':'';return `<article class="experiment-card ${complete?'completed':'validating'}"><span class="experiment-node"></span><div class="experiment-card-head"><div><span>ROUND ${String(e.round_no).padStart(2,'0')} · ${esc(stages[e.stage])}</span><b>${esc(e.hypothesis)}</b></div><em class="experiment-status ${complete?'done':''}">${complete?'已完成':'验证中'}</em></div><div class="experiment-meta"><span><i>目标用户</i>${esc(e.target_user)}</span><span><i>验证方式</i>${esc(e.method)}</span><span><i>成功阈值</i>${thresholdLabel(e)}</span><span><i>周期</i>${esc(e.start_date)} — ${esc(e.end_date)}</span></div>${complete?`<div class="experiment-result"><div><span class="result-chip ${tone}">${result}</span><b>${Number(e.actual_value).toLocaleString('zh-CN')} ${esc(e.threshold_unit)}</b><small>${esc(e.actual_data)}</small></div><p><i>数据来源</i>${sourceMarkup(e.data_source)}</p><p><i>验证结论</i>${esc(e.conclusion)}</p><p><i>最终决策</i><strong>${esc(e.decision)}</strong></p><p class="learning"><i>关键学习</i>${esc(e.key_learning)}</p></div>`:`<p class="experiment-waiting">实验进行中，结束后填写实际数据、验证结论与最终决策。</p>`}${isAdmin?`<button class="experiment-result-btn" data-experiment-result="${e.id}" data-project="${p.id}">${complete?'维护实验结果':'填写实验结果'} →</button>`:''}</article>`}).join(''):'<p class="empty-inline experiment-empty">暂无验证实验。先把假设、用户、方式和成功阈值写清楚，再开始验证。</p>'}
function gateChecklist(p){const status=gateStatus(p),templateGates=(p.templateGates||[]).filter(g=>g.stage===p.stage),templateDone=templateGates.filter(g=>g.completed).length,total=status.total+templateGates.length,done=status.done+templateDone,missing=advanceRequirements(p);return `<div class="gate-summary"><div><span>${esc(stages[p.stage])}完成度</span><b>${done} / ${total}</b></div><div class="gate-progress"><i style="width:${total?Math.round(done/total*100):0}%"></i></div></div><div class="gate-list">${status.definitions.map(g=>`<label class="gate-item ${status.completed.has(g.gate_key)?'completed':''}"><input type="checkbox" data-gate="${esc(g.gate_key)}" data-stage="${g.stage}" data-project="${p.id}" ${status.completed.has(g.gate_key)?'checked':''} ${isAdmin?'':'disabled'}><span><b>${esc(g.label)}</b><small>${g.required?'必填门槛':'建议门槛'}</small></span></label>`).join('')}${templateGates.map(g=>`<label class="gate-item ${g.completed?'completed':''}"><input type="checkbox" data-template-gate="${g.id}" data-project="${p.id}" ${g.completed?'checked':''} ${isAdmin?'':'disabled'}><span><b>${esc(g.label)}</b><small>模板专属门槛</small></span></label>`).join('')}</div>${missing.length?`<div class="gate-blocker"><b>暂不能推进，还缺少 ${missing.length} 项</b><ul>${missing.map(item=>`<li class="${item.type==='experiment'?'experiment-required':item.type==='metric'?'metric-required':''}">${esc(item.label)}</li>`).join('')}</ul></div>`:'<div class="gate-ready"><b>阶段门槛、验证实验与关键指标均已完成</b><span>可以申请推进至相邻的下一阶段。</span></div>'}`}
function stageTimeline(p){return p.history?.length?p.history.map(h=>{const initial=h.from_stage===null,from=initial?'项目创建':stages[h.from_stage],to=stages[h.to_stage],kind={initial:'创建',advance:'推进',rollback:'回退',cross_stage:'跨阶段'}[h.change_type]||'调整';return `<div class="timeline-item ${h.change_type}"><span class="timeline-dot"></span><div><div class="timeline-top"><b>${esc(kind)} · ${esc(from)}${initial?'':' → '}${initial?'进入 ':''}${esc(to)}</b><time>${formatBusinessDateTime(h.created_at,{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time></div><p>${esc(h.reason)}</p><small>${esc(h.actor_email)}</small></div></div>`}).join(''):'<p class="empty-inline">暂无阶段历史。</p>'}

function projectTrendCards(p){const related=trendsFor(p.id);return related.length?related.map(t=>{const mapping=t.mappings.find(r=>r.project_id===p.id),source=/^https?:\/\//i.test(t.original_url)?`<a href="${esc(t.original_url)}" target="_blank" rel="noreferrer">查看原始来源 ↗</a>`:'<span class="legacy-source">历史数据未提供原始链接</span>';return `<article class="project-trend-card"><div class="project-trend-head"><div><span>${esc(t.source_platform)} · 发现于 ${esc(t.discovered_on)}</span><b># ${esc(t.name)}</b></div><em>${esc(t.status)}</em></div><div class="project-trend-metrics"><span><i>内容 / 搜索量</i>${esc(t.volume)}</span><span><i>增长率</i>${esc(t.growth)}</span><span><i>可信度</i>${esc(t.confidence)}</span></div><p><i>目标人群</i>${esc(t.target_audience)}</p><p><i>信号说明</i>${esc(t.signal_note)}</p><p class="data-hypothesis"><i>本项目验证假设</i>${esc(mapping?.hypothesis||'待补充')}</p>${source}</article>`}).join(''):'<p class="data-hypothesis">尚未关联趋势；可从“正在验证的趋势”中建立关系。</p>'}

function setBackgroundInert(active){$('main').inert=active;$('.sidebar').inert=active;document.body.classList.toggle('drawer-open',active)}
function focusDrawer(drawer){setTimeout(()=>$('.close-btn',drawer)?.focus(),0)}

function openDrawer(p,returnTarget=null){
  if(!p)return;
  if(!$('#detailDrawer').classList.contains('open'))drawerReturnFocus=returnTarget||document.activeElement;
  const requirements=advanceRequirements(p),stageMarkers=stages.map((name,i)=>`<span class="stage-marker ${i<p.stage?'done':''} ${i===p.stage?'active':''}"><i>${i+1}</i>${esc(name)}</span>`).join(''),health=projectHealth(p),task=nextTask(p),logs=state.activity.filter(a=>a.project_id===p.id||a.text.includes(p.name));
  const overview=`<section class="drawer-block"><div class="drawer-section-head"><h3>项目假设</h3>${isAdmin?`<button data-edit-project="${p.id}">编辑资料</button>`:''}</div><p>${esc(p.intro)}</p><div class="project-taxonomy"><span>${esc(p.category||'未分类')}</span><b>→</b><span>${esc(p.subcategory||'待补充')}</span></div><div class="overview-grid"><span><i>负责人</i>${esc(p.owner)}</span><span><i>参与人员</i>${esc(p.members)}</span><span><i>当前阶段</i>${esc(stages[p.stage])} · ${projectDwell(p)} 天</span><span><i>健康状态</i><b class="health-pill ${healthClass(health)}">${health}</b></span><span class="wide"><i>自动下一步</i>${task?`${esc(task.title)} · ${esc(task.owner)} · ${esc(task.due)}`:'暂无未完成任务'}</span></div></section><section class="drawer-block"><div class="drawer-section-head"><h3>关联趋势</h3><span>${trendsFor(p.id).length} 条</span></div><div class="project-trend-list">${projectTrendCards(p)}</div></section><section class="drawer-block gate-block"><div class="drawer-section-head"><h3>${esc(stages[p.stage])}阶段门槛</h3><span>${p.progress}% 总进度</span></div>${gateChecklist(p)}</section><section class="drawer-block"><h3>项目流转</h3><div class="stage-path">${stageMarkers}</div>${isAdmin?`<div class="stage-action-stack"><button class="primary-btn advance-btn" data-advance="${p.id}" ${p.stage===4||requirements.length?'disabled':''}>${p.stage===4?'已进入最终阶段':requirements.length?`缺少 ${requirements.length} 项推进条件`:'推进至下一阶段 →'}</button><button class="stage-admin-btn" data-admin-stage="${p.id}">管理员回退 / 跨阶段调整</button></div>`:''}</section>`;
  const validation=`<section class="drawer-block experiment-block"><div class="drawer-section-head"><h3>验证实验</h3>${isAdmin?`<button data-add-experiment="${p.id}">＋ 新建一轮</button>`:''}</div><div class="experiment-timeline">${experimentTimeline(p)}</div></section><section class="drawer-block"><div class="drawer-section-head"><h3>结构化验证指标</h3>${isAdmin?`<button data-add-metric="${p.id}">＋ 添加</button>`:''}</div><div class="metric-data-list">${p.metrics.length?p.metrics.map(m=>metricCard(m,p)).join(''):'<p class="empty-inline">尚未录入验证指标。</p>'}</div></section>`;
  const groups=[['待办',p.tasks.filter(t=>!t.done&&t.due>=today())],['逾期',p.tasks.filter(t=>!t.done&&t.due<today())],['已完成',p.tasks.filter(t=>t.done)]];const tasks=`<section class="drawer-block"><div class="drawer-section-head"><h3>项目任务</h3>${isAdmin?`<button data-add-task="${p.id}">＋ 添加</button>`:''}</div>${groups.map(([name,items])=>`<div class="task-group"><h4>${name} <span>${items.length} 项</span></h4><div class="task-list">${items.length?items.map(t=>taskRow(t,p)).join(''):'<p class="empty-inline">暂无</p>'}</div></div>`).join('')}</section>`;
  const records=`<section class="drawer-block"><h3>阶段变化</h3><div class="stage-timeline">${stageTimeline(p)}</div></section><section class="drawer-block"><h3>资料、决策与操作日志</h3><div class="activity-list">${logs.map(a=>`<p><time>${formatBusinessDateTime(a.created_at)}</time><b>${esc(a.type)}</b>${esc(a.text)}<small>${esc(a.actor_email||'system')}</small></p>`).join('')||'<p>暂无记录。</p>'}</div></section>`;
  $('#drawerEyebrow').innerHTML=`${esc(stages[p.stage])} · 停留 ${projectDwell(p)} 天 · <span class="health-pill ${healthClass(health)}">${health}</span>`;$('#drawerTitle').textContent=p.name;
  $('#drawerContent').innerHTML=`<div class="drawer-primary-actions">${isAdmin?`<button data-edit-project="${p.id}">编辑</button><button data-add-task="${p.id}">＋ 任务</button>${p.stage===4?`<button data-extract-template="${p.id}">提炼模板</button>`:''}`:'<span>公开只读</span>'}</div><nav class="drawer-tabs" aria-label="项目详情标签">${[['overview','概览'],['validation','验证实验'],['tasks','任务'],['records','记录']].map(([id,label])=>`<button type="button" data-drawer-tab="${id}" class="${activeDrawerTab===id?'active':''}">${label}</button>`).join('')}</nav><div class="drawer-tab-panel" data-tab-panel="overview" ${activeDrawerTab==='overview'?'':'hidden'}>${overview}</div><div class="drawer-tab-panel" data-tab-panel="validation" ${activeDrawerTab==='validation'?'':'hidden'}>${validation}</div><div class="drawer-tab-panel" data-tab-panel="tasks" ${activeDrawerTab==='tasks'?'':'hidden'}>${tasks}</div><div class="drawer-tab-panel" data-tab-panel="records" ${activeDrawerTab==='records'?'':'hidden'}>${records}</div>${isAdmin?`<div class="drawer-actions"><button class="danger-btn" data-delete-project="${p.id}">删除项目</button></div>`:''}`;
  $('#detailDrawer').classList.add('open');$('#drawerOverlay').classList.add('open');$('#detailDrawer').setAttribute('aria-hidden','false');setBackgroundInert(true);focusDrawer($('#detailDrawer'));
}

function closeDrawer(){const wasOpen=$('#detailDrawer').classList.contains('open');$('#detailDrawer').classList.remove('open');$('#drawerOverlay').classList.remove('open');$('#detailDrawer').setAttribute('aria-hidden','true');if(wasOpen){setBackgroundInert(false);drawerReturnFocus?.focus();drawerReturnFocus=null}}
function setStage(stage){selectedStage=stage;const tabs=$$('.stage-tab');tabs.forEach((tab,index)=>{const active=tab.dataset.stage===String(stage);tab.classList.toggle('active',active);tab.setAttribute('role','tab');tab.setAttribute('aria-selected',String(active));tab.setAttribute('aria-controls','projectRows');tab.tabIndex=active||stage==='all'&&index===0?0:-1});const all=stage==='all';$('#allStages').classList.toggle('active',all);$('#allStages').setAttribute('aria-pressed',String(all));renderProjects()}
function renderStageDialogState(){const p=project(pendingProject);if(!p)return;const target=pendingStageMode==='admin'?Number($('#stageTarget').value):pendingStage,delta=target-p.stage,forward=delta>0,missing=forward?advanceRequirements(p):[],reasonRequired=delta<0||Math.abs(delta)>1;pendingStage=target;$('#advanceTitle').textContent=`${delta<0?'回退':delta>1?'跨阶段调整':'推进'}至「${stages[target]}」` ;$('#advanceCopy').textContent=`「${p.name}」将从「${stages[p.stage]}」调整至「${stages[target]}」。本次变更会写入不可变更的阶段历史。`;$('#stageReasonLabel').textContent=reasonRequired?'调整原因（必填）':'推进说明（选填）';$('#stageReason').required=reasonRequired;$('#stageReasonHint').textContent=reasonRequired?'回退或跨阶段调整必须说明依据与后续处理。':'不填写时，将记录为“阶段门槛、验证实验与关键指标均已完成”。';$('#stageGateSummary').innerHTML=missing.length?`<div class="stage-dialog-blocked"><b>无法进入后续阶段，还缺少：</b><ul>${missing.map(item=>`<li>${esc(item.label)}</li>`).join('')}</ul></div>`:'<div class="stage-dialog-ready">阶段门槛、验证实验与关键指标检查通过</div>';$('#stageSubmit').disabled=Boolean(missing.length);$('#stageSubmit').textContent=missing.length?'推进条件未完成':delta<0?'确认回退 →':delta>1?'确认跨阶段调整 →':'确认推进 →'}
function requestStage(projectId,target,mode='advance'){if(!requireAdmin())return;const p=project(projectId);if(!p)return;pendingProject=projectId;pendingStageMode=mode;$('#advanceForm').reset();const admin=mode==='admin';$('#stageTargetWrap').hidden=!admin;if(admin){const options=stages.map((name,i)=>({name,i})).filter(x=>x.i!==p.stage&&x.i!==p.stage+1);if(!options.length){notice('当前没有可用的回退或跨阶段目标。');return}$('#stageTarget').innerHTML=options.map(x=>`<option value="${x.i}">${x.i<p.stage?'回退':'跨阶段'} · ${x.name}</option>`).join('');pendingStage=options[0].i}else{pendingStage=target;if(target!==p.stage+1){notice('默认推进只能进入相邻的下一阶段。');return}}renderStageDialogState();$('#advanceDialog').showModal()}

function populateCategories(){const select=$('#projectCategory');select.innerHTML=`<option value="">选择一级类别</option>${Object.keys(appCategories).map(name=>`<option value="${name}">${name}</option>`).join('')}`}
function setSubcategories(category,value=''){const select=$('#projectSubcategory'),items=appCategories[category]||[];select.disabled=!items.length;select.innerHTML=items.length?`<option value="">选择二级分类</option>${items.map(name=>`<option value="${name}">${name}</option>`).join('')}`:'<option value="">请先选择项目类别</option>';select.value=items.includes(value)?value:''}
function openNewProject(){if(!requireAdmin())return;$('#projectForm').reset();$('#editProjectId').value='';setSubcategories('');$('#projectDialogTitle').textContent='创建新的增长项目';$('#projectSubmit').textContent='创建并进入立项 →';$('#projectDialog').showModal()}
function openCreationChoice(templateId=''){if(!requireAdmin())return;selectedTemplate=templateId;$('#creationTemplateWrap').hidden=!templateId;$('#creationTemplateActions').hidden=!templateId;$('#creationTemplate').value=templateId;$('#creationChoiceDialog').showModal()}
function openEditProject(p){if(!requireAdmin())return;$('#editProjectId').value=p.id;$('#newProjectName').value=p.name;$('#newProjectIntro').value=p.intro;$('#projectCategory').value=appCategories[p.category]?p.category:'';setSubcategories($('#projectCategory').value,p.subcategory);$('#projectOwner').value=p.owner;$('#projectMembers').value=p.members;$('#projectDialogTitle').textContent='编辑项目资料';$('#projectSubmit').textContent='保存项目资料 →';$('#projectDialog').showModal()}
function ensureSelectValue(node,value){if(value&&![...node.options].some(option=>option.value===value))node.add(new Option(value,value));node.value=value||''}
function renderTrendProjectPicker(t=null){$('#trendProjects').innerHTML=state.projects.map(p=>{const mapping=t?.mappings.find(r=>r.project_id===p.id),checked=Boolean(mapping);return `<div class="project-pick ${checked?'selected':''}" data-picker-project="${p.id}"><label><input type="checkbox" ${checked?'checked':''}><span><b>${esc(p.name)}</b><small>${esc(p.category)} / ${esc(p.subcategory)}</small></span></label><textarea rows="2" placeholder="该项目准备如何利用并验证这条趋势" ${checked?'required':'disabled'}>${esc(mapping?.hypothesis||'')}</textarea></div>`}).join('')||'<p class="empty-inline">请先创建项目，再建立趋势关系。</p>'}
function fillTrendForm(trendId=''){const t=state.trends.find(item=>item.id===trendId)||null;$('#trendExisting').value=t?.id||'';$('#trendDialogTitle').textContent=t?'维护趋势与项目关系':'建立趋势与项目关系';$('#trendSubmit').textContent=t?'保存趋势与关联 →':'创建趋势并关联 →';$('#trendName').value=t?.name||'';ensureSelectValue($('#trendPlatform'),t?.source_platform||'');$('#trendUrl').value=t?.original_url||'';$('#trendDiscovered').value=t?.discovered_on||today();$('#trendVolume').value=t?.volume==='待录入'?'':t?.volume||'';$('#trendGrowth').value=t?.growth==='待录入'?'':t?.growth||'';$('#trendAudience').value=t?.target_audience==='待补充'?'':t?.target_audience||'';$('#trendSignal').value=t?.signal_note==='待补充'?'':t?.signal_note||'';ensureSelectValue($('#trendConfidence'),t?.confidence||'');ensureSelectValue($('#trendStatus'),t?.status||'');renderTrendProjectPicker(t)}
function openTrendDialog(trendId=''){if(!requireAdmin())return;if(!state.projects.length){notice('请先创建项目，再建立趋势关系。');return}$('#trendForm').reset();$('#trendExisting').innerHTML=`<option value="">＋ 创建新趋势</option>${state.trends.map(t=>`<option value="${t.id}">${esc(t.name)} · ${t.projectIds.length} 个项目</option>`).join('')}`;fillTrendForm(trendId);$('#trendDialog').showModal()}
function localDateTime(date=new Date()){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:BUSINESS_TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date),v=Object.fromEntries(parts.filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));return `${v.year}-${v.month}-${v.day}T${v.hour}:${v.minute}`}
function toggleInitialObservation(show){$('#metricInitialObservation').hidden=!show;$$('input,textarea,select',$('#metricInitialObservation')).forEach(node=>node.disabled=!show)}
function openMetric(projectId,metricId=''){if(!requireAdmin())return;const p=project(projectId),m=metricId?p.metrics.find(x=>x.id===metricId):null;$('#metricForm').reset();$('#metricProjectId').value=projectId;$('#metricIndex').value=metricId;$('#metricDialogTitle').textContent=m?'维护指标定义':'添加结构化指标';$('#metricStageNote').textContent=m?'维护单位、目标和关键属性；历史周期数据不会被覆盖。':`指标默认归属当前「${stages[p.stage]}」阶段，并保存首期观测数据。`;$('#metricName').value=m?.name||'';$('#metricUnit').value=m?.unit||'';$('#metricBaseline').value=m?.baseline_value??'';$('#metricTarget').value=m?.target_value??'';$('#metricOperator').value=m?.comparison_operator||'>=';$('#metricStage').innerHTML=stages.map((name,i)=>`<option value="${i}">${i+1}. ${name}</option>`).join('');$('#metricStage').value=String(m?.stage??p.stage);$('#metricIsKey').checked=Boolean(m?.is_key);toggleInitialObservation(!m);if(!m){$('#metricPeriodStart').value=today();$('#metricPeriodEnd').value=today();$('#metricMeasuredAt').value=localDateTime()}$('#metricSubmit').textContent=m?'保存指标定义 →':'创建指标并保存首期数据 →';$('#metricDialog').showModal()}
function openMetricObservation(projectId,metricId){if(!requireAdmin())return;const p=project(projectId),m=p?.metrics.find(item=>item.id===metricId),latest=m&&latestObservation(m);if(!m)return;$('#metricObservationForm').reset();$('#metricObservationProjectId').value=p.id;$('#metricObservationMetricId').value=m.id;$('#metricObservationTitle').textContent=`录入「${m.name}」新一期数据`;$('#metricObservationContext').textContent=`单位 ${m.unit} · 目标 ${metricOperatorLabel(m.comparison_operator)} ${Number(m.target_value).toLocaleString('zh-CN')} ${m.unit}`;$('#observationPeriodStart').value=today();$('#observationPeriodEnd').value=today();$('#observationMeasuredAt').value=localDateTime();$('#observationSourceName').value=latest?.source_name||'';$('#observationSourceUrl').value=latest?.source_url||'';$('#observationMethodology').value=latest?.methodology||'';$('#metricObservationDialog').showModal()}
function openTask(projectId){if(!requireAdmin())return;$('#taskForm').reset();$('#taskProjectId').value=projectId;$('#taskDue').value=today();$('#taskDialog').showModal()}
function lines(value){return String(value||'').split('\n').map(v=>v.trim()).filter(Boolean)}
function openTemplateDialog(sourceProjectId=''){if(!requireAdmin())return;const p=project(sourceProjectId);$('#templateForm').reset();$('#templateSourceProject').value=sourceProjectId;$('#templateDialogTitle').textContent=p?`从「${p.name}」提炼模板`:'新建验证模板';if(p){$('#templateName').value=`${p.category||'项目'}验证模板`;$('#templateOpportunity').value=p.subcategory||p.category||'';$('#templateAudience').value=trendsFor(p.id).map(t=>t.target_audience).filter(Boolean).join('；')||'待补充目标用户';$('#templateHypotheses').value=p.experiments.map(e=>e.hypothesis).join('\n')||p.intro;$('#templateMethods').value=[...new Set(p.experiments.map(e=>e.method))].join('\n')||'用户访谈 / 问卷';$('#templateGates').value=state.gateDefinitions.map(g=>`${stages[g.stage]} | ${g.label}`).join('\n');$('#templateMetrics').value=p.metrics.map(m=>`${m.name} | ${m.unit} | ${m.comparison_operator} | ${m.target_value} | ${m.stage}`).join('\n')||'核心转化率 | % | >= | 10 | 2';$('#templateThresholds').value=p.experiments.map(e=>`${e.hypothesis}：${e.threshold_operator} ${e.threshold_value} ${e.threshold_unit}`).join('\n')||'关键指标达到设定目标';$('#templateCycle').value=`${Math.max(1,Math.ceil(daysBetween(p.created_at)/7))} 周`;$('#templateTasks').value=p.tasks.map(t=>`${t.title} | ${t.stage||0} | 7 | ${t.priority||'中'}`).join('\n')||'完成首轮用户验证 | 0 | 7 | 高';$('#templateFailures').value=p.experiments.filter(e=>e.threshold_met===false).map(e=>e.key_learning||e.conclusion).join('\n')||'样本不足\n信号与目标用户不匹配'}$('#templateDialog').showModal()}
function openExperiment(projectId){if(!requireAdmin())return;const p=project(projectId);$('#experimentForm').reset();$('#experimentProjectId').value=p.id;$('#experimentMethod').innerHTML=experimentMethods.map(name=>`<option value="${name}">${name}</option>`).join('');$('#experimentStart').value=today();$('#experimentEnd').value=shiftDayKey(today(),7);$('#experimentDialogTitle').textContent=`新建第 ${p.experiments.length+1} 轮验证实验`;$('#experimentStageNote').textContent=`本轮固定归属「${stages[p.stage]}」阶段`;$('#experimentDialog').showModal()}
function openExperimentResult(projectId,experimentId){if(!requireAdmin())return;const p=project(projectId),e=p.experiments.find(item=>item.id===experimentId);if(!e)return;$('#experimentResultForm').reset();$('#experimentResultProjectId').value=p.id;$('#experimentResultId').value=e.id;$('#experimentResultTitle').textContent=`第 ${e.round_no} 轮实验结果`;$('#experimentResultHypothesis').textContent=e.hypothesis;$('#experimentResultThreshold').textContent=`成功阈值 ${e.threshold_operator} ${Number(e.threshold_value).toLocaleString('zh-CN')} ${e.threshold_unit}`;$('#experimentActualValue').value=e.actual_value??'';$('#experimentActualData').value=e.actual_data||'';$('#experimentDataSource').value=e.data_source||'';$('#experimentConclusion').value=e.conclusion||'';$('#experimentDecision').innerHTML=`<option value="">选择最终决策</option>${experimentDecisions.map(name=>`<option value="${name}">${name}</option>`).join('')}`;$('#experimentDecision').value=e.decision||'';$('#experimentLearning').value=e.key_learning||'';renderExperimentPreview();$('#experimentResultDialog').showModal()}
function compareThreshold(actual,operator,target){return operator==='>='?actual>=target:operator==='>'?actual>target:operator==='<='?actual<=target:operator==='<'?actual<target:actual===target}
function renderExperimentPreview(){const p=project($('#experimentResultProjectId').value),e=p?.experiments.find(item=>item.id===$('#experimentResultId').value),raw=$('#experimentActualValue').value,node=$('#experimentAutoResult');if(!e||raw===''){node.textContent='输入实际数值后，系统将自动判断是否达到成功阈值。';node.className='experiment-auto-result';return}const actual=Number(raw),met=compareThreshold(actual,e.threshold_operator,Number(e.threshold_value));node.textContent=met?`自动判断：已达到成功阈值（${actual} ${e.threshold_unit}）`:`自动判断：未达到成功阈值（${actual} ${e.threshold_unit}）`;node.className=`experiment-auto-result ${met?'passed':'failed'}`}
function showDataGuide(){const grid=$('.data-guide-grid'),riskCard=[...grid.children].find(card=>$('h3',card)?.textContent==='风险项目');if(riskCard)$('p',riskCard).textContent='实时汇总逾期、即将到期、待确认、阶段超时、指标未达标、数据来源缺失和待管理层决策；项目数与具体问题数分开统计。';if(!$('.data-guide-extra',grid))grid.insertAdjacentHTML('beforeend','<article class="data-guide-extra"><h3>结构化指标</h3><p>指标定义与多期观测分开保存，数值、单位、样本量和来源均为独立字段；状态实时计算，关键指标未达标会阻止推进。</p></article><article class="data-guide-extra"><h3>验证模板</h3><p>模板创建项目时生成专属阶段门槛、推荐指标与标准任务；使用次数、来源项目和最终成功率均实时追溯。</p></article><article class="data-guide-extra"><h3>周期、单位与时区</h3><p>项目使用“个”、趋势使用“条”、验证使用“轮”、风险分别展示项目数与问题数、任务使用“项”；全部周期和逾期判断采用配置的业务时区。</p></article>');const list=state.activity.slice(0,8).map(a=>`<p><b>${esc(a.at)}</b><span>${esc(a.type)} · ${esc(a.text)}</span></p>`).join('');$('#dataLog').innerHTML=`<h3>最近线上记录</h3>${list||'<p>暂无记录</p>'}`;renderTrash();$('#dataDialog').showModal()}
function syncFilterUrl(){const params=new URLSearchParams();if(searchTerm)params.set('q',searchTerm);Object.entries(projectFilters).forEach(([key,value])=>{if(value&&(key!=='sort'||value!=='updated'))params.set(key,value)});if(selectedStage!=='all')params.set('funnel',selectedStage);if(selectedTrend)params.set('trend',selectedTrend);history.replaceState(null,'',`${location.pathname}${params.toString()?`?${params}`:''}${location.hash||'#projects'}`)}
function restoreFilters(){const params=new URLSearchParams(location.search);searchTerm=params.get('q')||'';$('#projectSearch').value=searchTerm;Object.keys(projectFilters).forEach(key=>{projectFilters[key]=params.get(key)||projectFilters[key]});selectedStage=params.get('funnel')||'all';selectedTrend=params.get('trend')||'';['category','stage','owner','health','flag','sort'].forEach(key=>{const node=$(`#${key==='sort'?'projectSort':`filter${key[0].toUpperCase()}${key.slice(1)}`}`);if(node)node.value=projectFilters[key]})}

$('#addProject').addEventListener('click',()=>openCreationChoice());$('#emptyAddProject').addEventListener('click',()=>openCreationChoice());$('#dataGuide').addEventListener('click',showDataGuide);$('#modelExplain').addEventListener('click',()=>$('#modelDialog').showModal());
$('#creationChoiceDialog').addEventListener('click',e=>{const mode=e.target.closest('[data-create-mode]')?.dataset.createMode;if(!mode)return;if(mode==='blank'){selectedTemplate='';$('#creationChoiceDialog').close();openNewProject()}else{$('#creationTemplateWrap').hidden=false;$('#creationTemplateActions').hidden=false}});$('#confirmTemplateProject').addEventListener('click',()=>{selectedTemplate=$('#creationTemplate').value;if(!selectedTemplate){notice('请先选择一个验证模板。');return}$('#creationChoiceDialog').close();openNewProject()});
$('#addTemplate').addEventListener('click',()=>openTemplateDialog());
$('#authButton').addEventListener('click',async()=>{if(isAdmin){await db.auth.signOut();notice('已退出管理员账号。')}else{$('#authPassword').value='';authMessage('');$('#authDialog').showModal()}});
$('#authButton').addEventListener('click',()=>$('#userMenu').removeAttribute('open'));
$('#helpMenu').addEventListener('click',e=>{if(e.target.tagName==='BUTTON')$('#helpMenu').removeAttribute('open')});
$('#projectCategory').addEventListener('change',e=>setSubcategories(e.target.value));
$$('.dialog-close,.cancel-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));

$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,password=$('#authPassword').value;setBusy(form,true);authMessage('正在验证…');const {data,error}=await db.auth.signInWithPassword({email:ADMIN_EMAIL,password});setBusy(form,false);if(error){authMessage(error.message,'error');return}currentUser=data.user;renderAuth();$('#authDialog').close();notice('管理员登录成功。')});
$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,id=$('#editProjectId').value,name=$('#newProjectName').value.trim(),intro=$('#newProjectIntro').value.trim(),category=$('#projectCategory').value,subcategory=$('#projectSubcategory').value,owner=$('#projectOwner').value.trim(),members=$('#projectMembers').value.trim();if(!name||!intro||!category||!subcategory||!owner||!members)return;setBusy(form,true);let savedId=id;const ok=await mutate(async()=>{if(id){const {error}=await db.from('projects').update({name,intro,category,subcategory,owner,members}).eq('id',id);if(error)throw error;await writeLog(id,`更新项目「${name}」的资料与分类`,'项目编辑')}else if(selectedTemplate){const {data,error}=await db.rpc('create_project_from_template',{p_template_id:selectedTemplate,p_name:name,p_intro:intro,p_category:category,p_subcategory:subcategory,p_owner:owner,p_members:members});if(error)throw error;savedId=data}else{const {data:p,error}=await db.from('projects').insert({name,intro,category,subcategory,owner,members}).select().single();if(error)throw error;savedId=p.id;await writeLog(p.id,`创建项目「${name}」，归类为「${category} / ${subcategory}」`,'新增')}},id?'项目资料已保存。':selectedTemplate?`「${name}」已从模板创建，门槛、指标与任务已生成。`:`「${name}」已立项，可继续建立趋势映射。`);setBusy(form,false);if(ok){selectedTemplate='';$('#projectDialog').close();form.reset();setSubcategories('');setStage(id?selectedStage:'0');const saved=project(savedId)||state.projects.find(p=>p.name===name);if(saved)openDrawer(saved)}});

$('#openTrendMap').addEventListener('click',()=>openTrendDialog());
$('#trendExisting').addEventListener('change',e=>fillTrendForm(e.target.value));
$('#trendProjects').addEventListener('change',e=>{const row=e.target.closest('[data-picker-project]');if(!row||e.target.type!=='checkbox')return;const input=$('textarea',row);input.disabled=!e.target.checked;input.required=e.target.checked;row.classList.toggle('selected',e.target.checked);if(e.target.checked)input.focus()});
$('#trendForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,trendId=$('#trendExisting').value,name=$('#trendName').value.trim(),links=$$('[data-picker-project]',$('#trendProjects')).filter(row=>$('input',row).checked).map(row=>({project_id:row.dataset.pickerProject,hypothesis:$('textarea',row).value.trim()})),trendData={p_trend_id:trendId||null,p_name:name,p_source_platform:$('#trendPlatform').value,p_original_url:$('#trendUrl').value.trim(),p_discovered_on:$('#trendDiscovered').value,p_volume:$('#trendVolume').value.trim(),p_growth:$('#trendGrowth').value.trim(),p_target_audience:$('#trendAudience').value.trim(),p_signal_note:$('#trendSignal').value.trim(),p_confidence:$('#trendConfidence').value,p_status:$('#trendStatus').value,p_links:links};if(!links.length){notice('至少选择一个关联项目。');return}if(links.some(link=>!link.hypothesis)){notice('请为每个关联项目填写独立验证假设。');return}setBusy(form,true);let savedTrendId='';const ok=await mutate(async()=>{const {data,error}=await db.rpc('save_trend_with_projects',trendData);if(error)throw error;savedTrendId=data;const logs=links.map(link=>({project_id:link.project_id,type:'趋势映射',text:`${trendId?'更新':'建立'}趋势「${name}」与项目「${project(link.project_id)?.name||'项目'}」的关系`,actor_email:currentUser.email}));const {error:logError}=await db.from('activity_logs').insert(logs);if(logError)throw logError},trendId?'趋势信息与项目关系已更新。':'趋势已创建并关联到所选项目。');setBusy(form,false);if(ok){$('#trendDialog').close();form.reset();selectedTrend=savedTrendId;renderAll()}});

$('.decision-strip').addEventListener('click',e=>{const card=e.target.closest('[data-command-filter]');if(!card)return;selectedCommandFilter=selectedCommandFilter===card.dataset.commandFilter?'':card.dataset.commandFilter;renderCounts();renderProjects();document.querySelector('#projects').scrollIntoView({behavior:'smooth',block:'start'})});
function closeRiskCenter(){const wasOpen=$('#riskDrawer').classList.contains('open');$('#riskDrawer').classList.remove('open');$('#riskOverlay').classList.remove('open');$('#riskDrawer').setAttribute('aria-hidden','true');if(wasOpen){setBackgroundInert(false);drawerReturnFocus?.focus();drawerReturnFocus=null}}
$('#riskClose').addEventListener('click',closeRiskCenter);$('#riskOverlay').addEventListener('click',closeRiskCenter);$('#riskLevelFilter').addEventListener('change',renderRiskCenter);$('#riskOwnerFilter').addEventListener('change',renderRiskCenter);$('#riskList').addEventListener('click',e=>{const id=e.target.closest('[data-risk-project]')?.dataset.riskProject;if(id){closeRiskCenter();openDrawer(project(id))}});
$('#templateList').addEventListener('click',e=>{const use=e.target.closest('[data-use-template]')?.dataset.useTemplate,view=e.target.closest('[data-template-project]')?.dataset.templateProject;if(use)openCreationChoice(use);if(view)openDrawer(project(view))});
$('#stageTabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const tabs=$$('.stage-tab'),current=Math.max(0,tabs.indexOf(document.activeElement)),next=e.key==='Home'?0:e.key==='End'?tabs.length-1:e.key==='ArrowRight'?(current+1)%tabs.length:(current-1+tabs.length)%tabs.length;e.preventDefault();setStage(tabs[next].dataset.stage);syncFilterUrl();tabs[next].focus()});
$('#stageTabs').addEventListener('click',e=>{const tab=e.target.closest('.stage-tab');if(tab){setStage(tab.dataset.stage);syncFilterUrl()}});$('#allStages').addEventListener('click',()=>{setStage('all');syncFilterUrl()});$('#projectSearch').addEventListener('input',e=>{searchTerm=e.target.value.trim();syncFilterUrl();renderProjects()});$('#clearFilter').addEventListener('click',()=>{selectedTrend='';selectedCommandFilter='';selectedStage='all';searchTerm='';Object.assign(projectFilters,{category:'',stage:'',owner:'',health:'',flag:'',sort:'updated'});$('#projectSearch').value='';['filterCategory','filterStage','filterOwner','filterHealth','filterFlag'].forEach(id=>$(`#${id}`).value='');$('#projectSort').value='updated';syncFilterUrl();setStage('all');renderCounts();renderTrends()});
['filterCategory','filterStage','filterOwner','filterHealth','filterFlag','projectSort'].forEach(id=>$(`#${id}`).addEventListener('change',e=>{const key=id==='projectSort'?'sort':id.replace('filter','').toLowerCase();projectFilters[key]=e.target.value;syncFilterUrl();renderProjects()}));
$('#projectRows').addEventListener('click',e=>{const row=e.target.closest('.project-row');if(row)openDrawer(project(row.dataset.project),row)});$('#projectRows').addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){const row=e.target.closest('.project-row');if(row){e.preventDefault();openDrawer(project(row.dataset.project),row)}}});
$('#trendList').addEventListener('click',e=>{const edit=e.target.closest('[data-edit-trend]');if(edit){openTrendDialog(edit.dataset.editTrend);return}const card=e.target.closest('.trend-card');if(!card)return;const t=state.trends.find(x=>x.id===card.dataset.trend);selectedTrend=selectedTrend===t.id?'':t.id;setStage('all');renderTrends();notice(selectedTrend?`已按关系筛选关联「${t.name}」的项目。`:'已显示全部项目。')});$('#resetTrend').addEventListener('click',()=>{selectedTrend='';renderProjects();renderTrends()});$('#drawerClose').addEventListener('click',closeDrawer);$('#drawerOverlay').addEventListener('click',closeDrawer);

$('#drawerContent').addEventListener('click',async e=>{const tab=e.target.closest('[data-drawer-tab]')?.dataset.drawerTab;if(tab){activeDrawerTab=tab;localStorage.setItem('projectDrawerTab',tab);$$('[data-drawer-tab]',$('#drawerContent')).forEach(b=>b.classList.toggle('active',b.dataset.drawerTab===tab));$$('[data-tab-panel]',$('#drawerContent')).forEach(p=>p.hidden=p.dataset.tabPanel!==tab);return}if(e.target.dataset.confirmTask){const p=project(e.target.dataset.project),task=p.tasks.find(t=>t.id===e.target.dataset.confirmTask);const ok=await mutate(async()=>{const {error}=await db.from('tasks').update({confirmation_status:'confirmed'}).eq('id',task.id);if(error)throw error;await writeLog(p.id,`负责人确认任务「${task.title}」`,'任务')},'任务已确认，相关风险已自动移除。');if(ok)openDrawer(project(p.id));return}if(e.target.dataset.extractTemplate)openTemplateDialog(e.target.dataset.extractTemplate);if(e.target.dataset.advance){const p=project(e.target.dataset.advance);requestStage(p.id,p.stage+1)}if(e.target.dataset.adminStage)requestStage(e.target.dataset.adminStage,null,'admin');if(e.target.dataset.addExperiment)openExperiment(e.target.dataset.addExperiment);if(e.target.dataset.experimentResult)openExperimentResult(e.target.dataset.project,e.target.dataset.experimentResult);if(e.target.dataset.addMetric)openMetric(e.target.dataset.addMetric);if(e.target.dataset.editMetric)openMetric(e.target.dataset.project,e.target.dataset.editMetric);if(e.target.dataset.addObservation)openMetricObservation(e.target.dataset.project,e.target.dataset.addObservation);if(e.target.dataset.addTask)openTask(e.target.dataset.addTask);if(e.target.dataset.editProject)openEditProject(project(e.target.dataset.editProject));if(e.target.dataset.deleteProject){const p=project(e.target.dataset.deleteProject);if(!confirm(`确认删除项目「${p.name}」？删除后可在“数据口径”中恢复。`))return;const ok=await mutate(async()=>{const {error}=await db.from('projects').update({deleted_at:new Date().toISOString()}).eq('id',p.id);if(error)throw error;await writeLog(p.id,`删除项目「${p.name}」`,'删除')},'项目已移入已删除列表。');if(ok)closeDrawer()}});
$('#drawerContent').addEventListener('change',async e=>{if(!isAdmin)return;const p=project(e.target.dataset.project);if(e.target.dataset.templateGate){const completed=e.target.checked,ok=await mutate(async()=>{const {error}=await db.rpc('set_project_template_gate',{p_gate_id:e.target.dataset.templateGate,p_completed:completed});if(error)throw error},completed?'模板阶段门槛已完成。':'模板阶段门槛已重新打开。');if(ok)openDrawer(project(p.id));return}if(e.target.dataset.gate){const stage=Number(e.target.dataset.stage),gateKey=e.target.dataset.gate,completed=e.target.checked;const ok=await mutate(async()=>{const {error}=await db.rpc('set_project_stage_gate',{p_project_id:p.id,p_stage:stage,p_gate_key:gateKey,p_completed:completed});if(error)throw error},completed?'阶段门槛已完成，项目进度已自动更新。':'阶段门槛已重新打开，项目进度已自动更新。');if(ok)openDrawer(project(p.id));return}if(!e.target.dataset.task)return;const task=p.tasks.find(t=>t.id===e.target.dataset.task),done=e.target.checked;const ok=await mutate(async()=>{const {error}=await db.from('tasks').update({done}).eq('id',task.id);if(error)throw error;await writeLog(p.id,`${done?'完成':'重新打开'}任务「${task.title}」`,'任务')},done?'任务已完成，相关风险已自动重算。':'任务已重新打开。');if(ok)openDrawer(project(p.id))});

$('#stageTarget').addEventListener('change',renderStageDialogState);
$('#advanceForm').addEventListener('submit',async e=>{e.preventDefault();if(!pendingProject||pendingStage===null)return;const form=e.currentTarget,p=project(pendingProject),target=pendingStage,reason=$('#stageReason').value.trim(),delta=target-p.stage;if((delta<0||Math.abs(delta)>1)&&!reason){$('#stageReason').focus();notice('回退或跨阶段调整必须填写原因。');return}setBusy(form,true);const ok=await mutate(async()=>{const {error}=await db.rpc('change_project_stage',{p_project_id:p.id,p_target_stage:target,p_reason:reason});if(error)throw error},`已更新为「${stages[target]}」，阶段历史已保存。`);setBusy(form,false);if(ok){$('#advanceDialog').close();openDrawer(project(p.id));pendingProject='';pendingStage=null;pendingStageMode='advance'}});

$('#metricForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,p=project($('#metricProjectId').value),metricId=$('#metricIndex').value,name=$('#metricName').value.trim(),creating=!metricId,periodStart=$('#metricPeriodStart').value,periodEnd=$('#metricPeriodEnd').value,payload={p_metric_id:metricId||null,p_project_id:p.id,p_name:name,p_unit:$('#metricUnit').value.trim(),p_baseline_value:Number($('#metricBaseline').value),p_target_value:Number($('#metricTarget').value),p_comparison_operator:$('#metricOperator').value,p_stage:Number($('#metricStage').value),p_is_key:$('#metricIsKey').checked,p_value:creating?Number($('#metricValue').value):null,p_period_start:creating?periodStart:null,p_period_end:creating?periodEnd:null,p_sample_size:creating?Number($('#metricSampleSize').value):null,p_source_name:creating?$('#metricSourceName').value.trim():null,p_source_url:creating?$('#metricSourceUrl').value.trim():'',p_measured_at:creating?$('#metricMeasuredAt').value:null,p_methodology:creating?$('#metricMethodology').value.trim():''};if(creating&&periodEnd<periodStart){notice('数据周期结束日期不能早于开始日期。');return}setBusy(form,true);const ok=await mutate(async()=>{const {error}=await db.rpc('save_metric_with_observation',payload);if(error)throw error;await writeLog(p.id,`${creating?'创建':'更新'}项目「${p.name}」的结构化指标「${name}」`,'指标')},creating?'指标与首期数据已保存。':'指标定义已更新，历史周期数据保持不变。');setBusy(form,false);if(ok){$('#metricDialog').close();openDrawer(project(p.id))}});

$('#metricObservationForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,p=project($('#metricObservationProjectId').value),m=p.metrics.find(item=>item.id===$('#metricObservationMetricId').value),periodStart=$('#observationPeriodStart').value,periodEnd=$('#observationPeriodEnd').value,payload={p_metric_id:m.id,p_project_id:p.id,p_name:m.name,p_unit:m.unit,p_baseline_value:Number(m.baseline_value),p_target_value:Number(m.target_value),p_comparison_operator:m.comparison_operator,p_stage:m.stage,p_is_key:m.is_key,p_value:Number($('#observationValue').value),p_period_start:periodStart,p_period_end:periodEnd,p_sample_size:Number($('#observationSampleSize').value),p_source_name:$('#observationSourceName').value.trim(),p_source_url:$('#observationSourceUrl').value.trim(),p_measured_at:$('#observationMeasuredAt').value,p_methodology:$('#observationMethodology').value.trim()};if(periodEnd<periodStart){notice('数据周期结束日期不能早于开始日期。');return}setBusy(form,true);const ok=await mutate(async()=>{const {error}=await db.rpc('save_metric_with_observation',payload);if(error)throw error;await writeLog(p.id,`为指标「${m.name}」录入 ${periodStart} 至 ${periodEnd} 数据`,'指标')},'新一期指标数据已保存，状态已自动重算。');setBusy(form,false);if(ok){$('#metricObservationDialog').close();openDrawer(project(p.id))}});

$('#experimentForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,p=project($('#experimentProjectId').value),start=$('#experimentStart').value,end=$('#experimentEnd').value,thresholdRaw=$('#experimentThresholdValue').value,experiment={project_id:p.id,round_no:0,stage:p.stage,hypothesis:$('#experimentHypothesis').value.trim(),target_user:$('#experimentTargetUser').value.trim(),method:$('#experimentMethod').value,threshold_operator:$('#experimentThresholdOperator').value,threshold_value:Number(thresholdRaw),threshold_unit:$('#experimentThresholdUnit').value.trim(),start_date:start,end_date:end,created_by:currentUser.email};if(!experiment.hypothesis||!experiment.target_user||!experiment.method||thresholdRaw===''||!Number.isFinite(experiment.threshold_value)||!experiment.threshold_unit||!start||!end)return;if(end<start){notice('结束日期不能早于开始日期。');return}setBusy(form,true);const ok=await mutate(async()=>{const {data,error}=await db.from('validation_experiments').insert(experiment).select().single();if(error)throw error;await writeLog(p.id,`创建第 ${data.round_no} 轮验证实验「${experiment.hypothesis}」`,'实验')},'验证实验已创建，状态为“验证中”。');setBusy(form,false);if(ok){$('#experimentDialog').close();openDrawer(project(p.id))}});

$('#experimentActualValue').addEventListener('input',renderExperimentPreview);
$('#experimentResultForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,p=project($('#experimentResultProjectId').value),experiment=p.experiments.find(item=>item.id===$('#experimentResultId').value),actualRaw=$('#experimentActualValue').value,actualValue=Number(actualRaw),result={actual_value:actualValue,actual_data:$('#experimentActualData').value.trim(),data_source:$('#experimentDataSource').value.trim(),conclusion:$('#experimentConclusion').value.trim(),decision:$('#experimentDecision').value,key_learning:$('#experimentLearning').value.trim(),completed_at:experiment.completed_at||new Date().toISOString()};if(actualRaw===''||!Number.isFinite(actualValue)||!result.actual_data||!result.data_source||!result.conclusion||!result.decision||!result.key_learning)return;const met=compareThreshold(actualValue,experiment.threshold_operator,Number(experiment.threshold_value));setBusy(form,true);const ok=await mutate(async()=>{const {error}=await db.from('validation_experiments').update(result).eq('id',experiment.id);if(error)throw error;await writeLog(p.id,`完成第 ${experiment.round_no} 轮验证实验，${met?'达到':'未达到'}成功阈值，决策「${result.decision}」`,'验证结论')},`实验结果已保存：${met?'达到':'未达到'}成功阈值。`);setBusy(form,false);if(ok){$('#experimentResultDialog').close();openDrawer(project(p.id))}});

$('#taskForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,p=project($('#taskProjectId').value),task={project_id:p.id,title:$('#taskTitle').value.trim(),owner:$('#taskOwner').value.trim(),due:$('#taskDue').value,criteria:$('#taskDone').value.trim(),priority:$('#taskPriority').value,confirmation_status:$('#taskConfirmation').value,stage:p.stage};if(!task.title||!task.owner||!task.due||!task.criteria)return;setBusy(form,true);const ok=await mutate(async()=>{const {error}=await db.from('tasks').insert(task);if(error)throw error;await writeLog(p.id,`为项目「${p.name}」添加任务「${task.title}」`,'任务')},'任务已添加；项目下一步已按截止日期和优先级自动重算。');setBusy(form,false);if(ok){$('#taskDialog').close();openDrawer(project(p.id))}});

$('#templateForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,sourceProjectId=$('#templateSourceProject').value,metrics=lines($('#templateMetrics').value).map(row=>{const [name,unit,operator,target,stage]=row.split('|').map(v=>v.trim());return {name,unit:unit||'自定义',operator:['>','>=','<','<='].includes(operator)?operator:'>=',target:Number(target)||0,baseline:0,stage:Math.min(4,Math.max(0,Number(stage)||0))}}),tasks=lines($('#templateTasks').value).map(row=>{const [title,stage,days,priority]=row.split('|').map(v=>v.trim());return {title,stage:Math.min(4,Math.max(0,Number(stage)||0)),days:Math.max(1,Number(days)||7),priority:['高','中','低'].includes(priority)?priority:'中',criteria:'按模板要求完成并留下可查验证证据'}}),payload={name:$('#templateName').value.trim(),opportunity_type:$('#templateOpportunity').value.trim(),target_audience:$('#templateAudience').value.trim(),common_hypotheses:lines($('#templateHypotheses').value),recommended_methods:lines($('#templateMethods').value),stage_gates:lines($('#templateGates').value),recommended_metrics:metrics,success_thresholds:lines($('#templateThresholds').value),estimated_cycle:$('#templateCycle').value.trim(),standard_tasks:tasks,common_failures:lines($('#templateFailures').value),source_project_id:sourceProjectId||null,created_by:currentUser.email};if(!payload.name||!payload.opportunity_type||!payload.target_audience||!metrics.length||!tasks.length)return;setBusy(form,true);const ok=await mutate(async()=>{const existing=state.templates.find(t=>t.name===payload.name);if(existing){const {error}=await db.from('validation_templates').update({...payload,version:existing.version+1}).eq('id',existing.id);if(error)throw error}else{const {error}=await db.from('validation_templates').insert(payload);if(error)throw error}if(sourceProjectId)await writeLog(sourceProjectId,`将项目「${project(sourceProjectId)?.name}」提炼为验证模板「${payload.name}」`,'模板')},'验证模板已保存，可用于创建新项目。');setBusy(form,false);if(ok)$('#templateDialog').close()});

$('#trashList').addEventListener('click',async e=>{const id=e.target.dataset.restoreProject;if(!id||!requireAdmin())return;const p=deletedProjects.find(x=>x.id===id);const ok=await mutate(async()=>{const {error}=await db.from('projects').update({deleted_at:null}).eq('id',id);if(error)throw error;await writeLog(id,`恢复项目「${p.name}」`,'恢复')},`「${p.name}」已恢复。`);if(ok){renderTrash();showDataGuide()}});
$('#exportData').addEventListener('click',()=>{if(!requireAdmin())return;const payload=JSON.stringify({exportedAt:new Date().toISOString(),projects:state.projects,trends:state.trends,projectTrendRelations:state.relations,activity:state.activity,deletedProjects},null,2),blob=new Blob([payload],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`company-project-board-${today()}.json`;a.click();URL.revokeObjectURL(url);notice('JSON 备份已导出。')});
document.addEventListener('keydown',e=>{const drawer=$('.detail-drawer.open');if(e.key==='Escape'){if($('#riskDrawer').classList.contains('open'))closeRiskCenter();else closeDrawer();return}if(e.key!=='Tab'||!drawer)return;const focusable=$$('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])',drawer).filter(el=>!el.disabled&&!el.hidden&&el.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});

async function initialize(){
  populateCategories();
  if(!db){setSync('线上配置缺失','error');renderAll();return}
  const {data}=await db.auth.getSession();currentUser=data.session?.user||null;renderAuth();
  db.auth.onAuthStateChange((_event,session)=>{currentUser=session?.user||null;renderAuth()});
  await loadData();
  restoreFilters();setStage(selectedStage);renderProjects();renderTrends();
  realtimeChannel=db.channel('company-project-board-live').on('postgres_changes',{event:'*',schema:'public'},()=>{clearTimeout(reloadTimer);reloadTimer=setTimeout(()=>loadData({quiet:true}),350)}).subscribe(status=>{if(status==='CHANNEL_ERROR')setSync('实时连接中断','error')});
}

initialize();
