-- Structured stage gates and immutable stage history.
-- Public visitors can read; only the fixed dashboard administrator can mutate through RPCs.

create table if not exists public.stage_gate_definitions (
  stage smallint not null check (stage between 0 and 4),
  gate_key text not null,
  label text not null,
  required boolean not null default true,
  position smallint not null default 0,
  primary key (stage, gate_key)
);

insert into public.stage_gate_definitions (stage, gate_key, label, required, position) values
  (0, 'problem_defined', '问题与目标用户已明确', true, 1),
  (0, 'owner_assigned', '负责人及参与人员已确认', true, 2),
  (0, 'success_metric', '成功标准与验证指标已定义', true, 3),
  (0, 'next_action', '下一步任务、负责人和截止日已建立', true, 4),
  (1, 'source_linked', '至少关联一个趋势来源', true, 1),
  (1, 'hypothesis_written', '产品假设已填写', true, 2),
  (1, 'audience_evidence', '目标人群及需求证据已记录', true, 3),
  (1, 'trend_conclusion', '趋势验证结论已形成', true, 4),
  (2, 'scope_locked', 'Demo 最小范围已锁定', true, 1),
  (2, 'demo_ready', 'Demo 主路径可操作', true, 2),
  (2, 'metric_instrumented', '核心指标及数据来源已配置', true, 3),
  (2, 'user_feedback', '完成首轮目标用户反馈', true, 4),
  (3, 'traffic_plan', '小流量测试方案与预算已确认', true, 1),
  (3, 'audience_segment', '测试人群分层已明确', true, 2),
  (3, 'conversion_result', '转化结果已记录', true, 3),
  (3, 'retention_result', '留存或复访结果已记录', true, 4),
  (4, 'growth_loop', '增长闭环成立', true, 1),
  (4, 'unit_economics', '单位经济模型已验证', true, 2),
  (4, 'playbook', '可复制执行手册已形成', true, 3),
  (4, 'scale_owner', '规模化负责人和资源已确认', true, 4)
on conflict (stage, gate_key) do update set
  label = excluded.label,
  required = excluded.required,
  position = excluded.position;

create table if not exists public.project_stage_gates (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  stage smallint not null check (stage between 0 and 4),
  gate_key text not null,
  completed boolean not null default false,
  completed_at timestamptz,
  completed_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (project_id, stage, gate_key),
  foreign key (stage, gate_key) references public.stage_gate_definitions(stage, gate_key)
);

create table if not exists public.stage_history (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  from_stage smallint check (from_stage between 0 and 4),
  to_stage smallint not null check (to_stage between 0 and 4),
  change_type text not null check (change_type in ('initial', 'advance', 'rollback', 'cross_stage')),
  reason text not null,
  actor_email text not null,
  created_at timestamptz not null default now()
);

drop trigger if exists project_stage_gates_set_updated_at on public.project_stage_gates;
create trigger project_stage_gates_set_updated_at before update on public.project_stage_gates
for each row execute function public.set_updated_at();

alter table public.stage_gate_definitions enable row level security;
alter table public.project_stage_gates enable row level security;
alter table public.stage_history enable row level security;

drop policy if exists "Public can read stage gate definitions" on public.stage_gate_definitions;
create policy "Public can read stage gate definitions" on public.stage_gate_definitions
for select using (true);

drop policy if exists "Public can read active project gates" on public.project_stage_gates;
create policy "Public can read active project gates" on public.project_stage_gates
for select using (exists (select 1 from public.projects p where p.id = project_id and p.deleted_at is null));

drop policy if exists "Public can read active stage history" on public.stage_history;
create policy "Public can read active stage history" on public.stage_history
for select using (exists (select 1 from public.projects p where p.id = project_id and p.deleted_at is null));

grant select on public.stage_gate_definitions, public.project_stage_gates, public.stage_history to anon, authenticated;
grant usage, select on sequence public.stage_history_id_seq to authenticated;

create or replace function public.set_project_stage_gate(
  p_project_id uuid,
  p_stage integer,
  p_gate_key text,
  p_completed boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_stage smallint;
  v_total integer;
  v_done integer;
begin
  if not public.is_dashboard_admin() then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;

  select stage into v_current_stage from public.projects
  where id = p_project_id and deleted_at is null for update;
  if not found then raise exception 'PROJECT_NOT_FOUND'; end if;
  if v_current_stage <> p_stage then raise exception 'GATE_STAGE_NOT_CURRENT'; end if;
  if not exists (select 1 from public.stage_gate_definitions where stage = p_stage and gate_key = p_gate_key) then
    raise exception 'GATE_NOT_FOUND';
  end if;

  insert into public.project_stage_gates (project_id, stage, gate_key, completed, completed_at, completed_by)
  values (p_project_id, p_stage::smallint, p_gate_key, p_completed,
    case when p_completed then now() else null end,
    case when p_completed then auth.jwt() ->> 'email' else null end)
  on conflict (project_id, stage, gate_key) do update set
    completed = excluded.completed,
    completed_at = excluded.completed_at,
    completed_by = excluded.completed_by;

  select count(*) into v_total from public.stage_gate_definitions where required;
  select count(*) into v_done
  from public.project_stage_gates g
  join public.stage_gate_definitions d on d.stage = g.stage and d.gate_key = g.gate_key
  where g.project_id = p_project_id and d.required and g.completed;

  update public.projects
  set progress = case when v_total = 0 then 0 else round(v_done * 100.0 / v_total)::smallint end
  where id = p_project_id;
end;
$$;

create or replace function public.change_project_stage(
  p_project_id uuid,
  p_target_stage integer,
  p_reason text default ''
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_from smallint;
  v_name text;
  v_missing integer;
  v_type text;
  v_reason text := nullif(trim(coalesce(p_reason, '')), '');
  v_actor text := coalesce(auth.jwt() ->> 'email', 'unknown');
begin
  if not public.is_dashboard_admin() then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;
  if p_target_stage is null or p_target_stage < 0 or p_target_stage > 4 then
    raise exception 'INVALID_TARGET_STAGE';
  end if;

  select stage, name into v_from, v_name from public.projects
  where id = p_project_id and deleted_at is null for update;
  if not found then raise exception 'PROJECT_NOT_FOUND'; end if;
  if v_from = p_target_stage then raise exception 'STAGE_UNCHANGED'; end if;

  if p_target_stage > v_from then
    select count(*) into v_missing
    from public.stage_gate_definitions d
    left join public.project_stage_gates g
      on g.project_id = p_project_id and g.stage = d.stage and g.gate_key = d.gate_key and g.completed
    where d.stage = v_from and d.required and g.id is null;
    if v_missing > 0 then raise exception 'STAGE_GATES_INCOMPLETE:%', v_missing; end if;
  end if;

  if p_target_stage < v_from and v_reason is null then raise exception 'ROLLBACK_REASON_REQUIRED'; end if;
  if abs(p_target_stage - v_from) > 1 and v_reason is null then raise exception 'CROSS_STAGE_REASON_REQUIRED'; end if;

  v_type := case
    when p_target_stage < v_from then 'rollback'
    when p_target_stage = v_from + 1 then 'advance'
    else 'cross_stage'
  end;
  v_reason := coalesce(v_reason, '当前阶段必填门槛全部完成');

  update public.projects set stage = p_target_stage::smallint where id = p_project_id;
  insert into public.stage_history (project_id, from_stage, to_stage, change_type, reason, actor_email)
  values (p_project_id, v_from, p_target_stage::smallint, v_type, v_reason, v_actor);
  insert into public.activity_logs (project_id, type, text, actor_email)
  values (p_project_id, '阶段流转', format('项目「%s」从「%s」调整至「%s」：%s', v_name,
    (array['立项','趋势验证','Demo MVP','小流量测试','规模转化'])[v_from + 1],
    (array['立项','趋势验证','Demo MVP','小流量测试','规模转化'])[p_target_stage + 1], v_reason), v_actor);
end;
$$;

grant execute on function public.set_project_stage_gate(uuid, integer, text, boolean) to authenticated;
grant execute on function public.change_project_stage(uuid, integer, text) to authenticated;

create or replace function public.record_initial_stage_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.stage_history (project_id, from_stage, to_stage, change_type, reason, actor_email)
  values (new.id, null, new.stage, 'initial', '项目创建并进入立项', coalesce(auth.jwt() ->> 'email', 'system'));
  return new;
end;
$$;

drop trigger if exists projects_record_initial_stage on public.projects;
create trigger projects_record_initial_stage after insert on public.projects
for each row execute function public.record_initial_stage_history();

insert into public.stage_history (project_id, from_stage, to_stage, change_type, reason, actor_email, created_at)
select p.id, null, p.stage, 'initial', '历史项目初始化', 'system', p.created_at
from public.projects p
where not exists (select 1 from public.stage_history h where h.project_id = p.id);

update public.projects p set progress = coalesce((
  select round(count(*) filter (where g.completed) * 100.0 / nullif(count(*), 0))::smallint
  from public.stage_gate_definitions d
  left join public.project_stage_gates g
    on g.project_id = p.id and g.stage = d.stage and g.gate_key = d.gate_key
  where d.required
), 0);

do $$
begin
  alter publication supabase_realtime add table public.project_stage_gates;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.stage_history;
exception when duplicate_object then null;
end $$;

create or replace function public.enforce_controlled_project_state()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.stage is distinct from old.stage and current_user not in ('postgres', 'supabase_admin') then
    raise exception 'USE_CHANGE_PROJECT_STAGE_RPC' using errcode = '42501';
  end if;
  if new.progress is distinct from old.progress and current_user not in ('postgres', 'supabase_admin') then
    raise exception 'PROJECT_PROGRESS_IS_AUTOMATIC' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists projects_enforce_controlled_state on public.projects;
create trigger projects_enforce_controlled_state before update of stage, progress on public.projects
for each row execute function public.enforce_controlled_project_state();
