-- 公司项目看板：线上数据结构与权限
-- Public visitors can read. Only the fixed administrator can mutate data.

create extension if not exists pgcrypto;

create or replace function public.is_dashboard_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((auth.jwt() ->> 'email') = 'luzw6688@gmail.com', false);
$$;

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  intro text not null,
  stage smallint not null default 0 check (stage between 0 and 4),
  trend text not null,
  owner text not null,
  members text not null,
  next_action text not null default '请添加第一个可验证任务。',
  progress smallint not null default 0 check (progress between 0 and 100),
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trends (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  name text not null,
  url text not null,
  growth text not null default '待录入',
  volume text not null default '待录入',
  hypothesis text not null default '待补充验证假设',
  status text not null default '等待趋势确认',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.metrics (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  name text not null,
  value text not null,
  source text not null,
  note text not null default '',
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  title text not null,
  owner text not null,
  due date not null,
  criteria text not null,
  done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  project_id uuid references public.projects(id) on delete set null,
  type text not null,
  text text not null,
  actor_email text,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at before update on public.projects
for each row execute function public.set_updated_at();

drop trigger if exists trends_set_updated_at on public.trends;
create trigger trends_set_updated_at before update on public.trends
for each row execute function public.set_updated_at();

drop trigger if exists metrics_set_updated_at on public.metrics;
create trigger metrics_set_updated_at before update on public.metrics
for each row execute function public.set_updated_at();

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at before update on public.tasks
for each row execute function public.set_updated_at();

alter table public.projects enable row level security;
alter table public.trends enable row level security;
alter table public.metrics enable row level security;
alter table public.tasks enable row level security;
alter table public.activity_logs enable row level security;

drop policy if exists "Public can read projects" on public.projects;
create policy "Public can read projects" on public.projects for select using (true);
drop policy if exists "Admin manages projects" on public.projects;
create policy "Admin manages projects" on public.projects for all
using (public.is_dashboard_admin()) with check (public.is_dashboard_admin());

drop policy if exists "Public can read trends" on public.trends;
create policy "Public can read trends" on public.trends for select using (true);
drop policy if exists "Admin manages trends" on public.trends;
create policy "Admin manages trends" on public.trends for all
using (public.is_dashboard_admin()) with check (public.is_dashboard_admin());

drop policy if exists "Public can read metrics" on public.metrics;
create policy "Public can read metrics" on public.metrics for select using (true);
drop policy if exists "Admin manages metrics" on public.metrics;
create policy "Admin manages metrics" on public.metrics for all
using (public.is_dashboard_admin()) with check (public.is_dashboard_admin());

drop policy if exists "Public can read tasks" on public.tasks;
create policy "Public can read tasks" on public.tasks for select using (true);
drop policy if exists "Admin manages tasks" on public.tasks;
create policy "Admin manages tasks" on public.tasks for all
using (public.is_dashboard_admin()) with check (public.is_dashboard_admin());

drop policy if exists "Public can read activity" on public.activity_logs;
create policy "Public can read activity" on public.activity_logs for select using (true);
drop policy if exists "Admin creates activity" on public.activity_logs;
create policy "Admin creates activity" on public.activity_logs for insert
with check (public.is_dashboard_admin());

grant usage on schema public to anon, authenticated;
grant select on public.projects, public.trends, public.metrics, public.tasks, public.activity_logs to anon;
grant select, insert, update, delete on public.projects, public.trends, public.metrics, public.tasks to authenticated;
grant select, insert on public.activity_logs to authenticated;
grant usage, select on sequence public.activity_logs_id_seq to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.projects;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.trends;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.metrics;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.tasks;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.activity_logs;
exception when duplicate_object then null;
end $$;

